[package]
name = "oam_cli"
description = "The oam binary."
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "oam"
path = "src/main.rs"

[dependencies]
oam_engine = { workspace = true }
oam_diagnostics = { workspace = true }
oam_loader = { workspace = true }
oam_ts = { workspace = true }
oam_mcp = { workspace = true }
clap = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
