#!/bin/bash
# =============================================================================
# oam mac platform-build orchestrator  (Tailscale leg)
# =============================================================================
# Runs the mac legs of the deleted GitHub workflows on the Tailscale-reachable
# Apple-Silicon MacBook Air (the same host that builds yaw's mac leg). The
# Linux leg lives in scripts/build-platforms-gcp-iap.sh; this script exists
# because the Air is a personal machine, not a GCP VM -- Tailscale stays the
# right tool for it. Tailnet SSH is plain OpenSSH with keepalive, so the
# remote work runs as ONE ssh call per mode (no IAP-style sub-step splitting).
#
# Modes (remote dispatch in scripts/build-remote.sh):
#   --mode=release (default)   mac-release: prep + gate + test + native arm64
#                              build + x86_64-apple-darwin build via the x64
#                              HOST toolchain under Rosetta 2 (the snapshot
#                              must be generated by a target-arch process --
#                              see build-remote.sh header).
#       pulls:  $ART/oam-aarch64-apple-darwin
#               $ART/oam-x86_64-apple-darwin      (unless OAM_SKIP_MAC_X64=1)
#               both codesigned, verified and JIT-smoked on the Air
#               (scripts/lib/mac-signing.sh), then checked here against the
#               Air's dist/mac-sha256.txt, which is pulled into a sibling of
#               $ART and never shipped
#   --mode=measure             mac-measure: prep + conformance + node-suite
#       pulls:  $ART/mac-arm64/{scorecard.json,CONFORMANCE.md,
#                               node-suite-scorecard.json,CONFORMANCE-NODE.md}
#   --mode=bench               mac-bench: prep + bench
#       pulls:  $ART/mac-arm64/{BENCHMARKS.md,results.json}
#
#   --preflight-only           with any mode: check the key file, then that the
#                              Air resolves, answers and accepts the key -- and
#                              stop there. Syncs nothing, builds nothing, prints
#                              nothing on stdout; exit 0 means a build could
#                              start. release-local.sh runs it before it tags.
#                              For --mode=release it also checks the mac
#                              signing decision, and with a pinned identity
#                              runs provision-mac-signing.sh --check on the
#                              Air (piped over ssh; nothing is synced).
#
# Usage (FAIL-CLOSED -- capture first, check the exit, THEN consume):
#   ART=$(./scripts/build-platforms-tailnet.sh) || { echo "mac leg failed"; exit 1; }
#   # Artifact dir = LAST stdout line; all progress goes to stderr.
#
# Host config (env; tailnet MagicDNS names or IPs -- `tailscale status`):
#   OAM_MAC_HOST      air.tailXXXX.ts.net   (required)
#   OAM_MAC_USER      account on the Mac    (required -- NOT $USER here)
#   OAM_MAC_KEY       SSH key path          (default: ~/.ssh/yaw_mac_air --
#                                            the key yaw's mac leg already
#                                            enrolled on the Air)
#   OAM_REMOTE_DIR    remote checkout path  (default: oam-build, under $HOME)
#   OAM_SKIP_MAC_X64=1  drop the x86_64-apple-darwin asset (release mode)
#   OAM_SIGN_REQUIRED=1 refuse an ad-hoc (bootstrap) mac build: with no SHA-1
#                       in scripts/mac-signing-identity.sha1, fail instead
#   OAM_SKIP_MAC_SIGN=1 ship the mac binaries without the codesign step (loud;
#                       honored even with OAM_SIGN_REQUIRED=1)
#   Env does not cross ssh: these three are forwarded on the mac-release ssh
#   line, each validated as 0 or 1 first. The keychain password stays on the
#   Air (~/.oam-signing, see scripts/provision-mac-signing.sh).
#
# Prereqs:
#   - Tailscale up on this box + the Air; ACLs allow SSH (22).
#   - Air toolchain: Xcode CLT; Rosetta 2 for the x64 leg (build-remote.sh
#     names the install command if missing). rustup auto-installs on first
#     prep, and so does the conformance oracle: exactly the Node in
#     .node-version, from nodejs.org into ~/.cache/oam-node. The Air's own
#     node (/usr/local/bin, Homebrew's node@22) is NOT used -- see
#     scripts/lib/node-pin.sh.
# =============================================================================

set -euo pipefail

MODE="release"
PREFLIGHT_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --mode=release|--mode=measure|--mode=bench|--mode=surface-gaps) MODE="${arg#--mode=}" ;;
    --preflight-only) PREFLIGHT_ONLY=1 ;;
    -h|--help)
      awk 'NR==1{next} !/^#/{exit} {sub(/^# ?/, ""); print}' "$0"
      exit 0
      ;;
    *) echo "unknown arg: $arg (want --mode=release|measure|bench|surface-gaps, --preflight-only)" >&2; exit 1 ;;
  esac
done

MAC_HOST="${OAM_MAC_HOST:?set OAM_MAC_HOST to the MacBook Air tailnet name or IP}"
MAC_USER="${OAM_MAC_USER:?set OAM_MAC_USER to the account on the MacBook Air (NOT \$USER from this box)}"
MAC_KEY="${OAM_MAC_KEY:-$HOME/.ssh/yaw_mac_air}"
REMOTE_DIR="${OAM_REMOTE_DIR:-oam-build}"
SKIP_MAC_X64="${OAM_SKIP_MAC_X64:-0}"
SIGN_REQUIRED="${OAM_SIGN_REQUIRED:-0}"
SKIP_MAC_SIGN="${OAM_SKIP_MAC_SIGN:-0}"

RED='\033[0;31m'; GRN='\033[0;32m'; YEL='\033[1;33m'; CYA='\033[1;36m'; NC='\033[0m'
ok()  { echo -e "${GRN}  [ok]${NC} $*" >&2; }
warn(){ echo -e "${YEL}  [warn]${NC} $*" >&2; }
fail(){ echo -e "${RED}  [fail]${NC} $*" >&2; exit 1; }
step(){ echo -e "\n${CYA}=== $* ===${NC}" >&2; }

# These go into the remote shell's command line verbatim (the mac-release ssh
# call below), so nothing but 0 or 1 may reach it.
for knob in "OAM_SKIP_MAC_X64=$SKIP_MAC_X64" "OAM_SIGN_REQUIRED=$SIGN_REQUIRED" "OAM_SKIP_MAC_SIGN=$SKIP_MAC_SIGN"; do
  case "${knob#*=}" in
    0|1) ;;
    *) fail "${knob%%=*} must be 0 or 1, not '${knob#*=}' -- it is forwarded to the Mac's shell" ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
# shellcheck source=lib/src-sync.sh
. "$SCRIPT_DIR/lib/src-sync.sh"
# disk_needs_reclaim / disk_below_floor -- the same thresholds as the linux leg.
# shellcheck source=lib/iap-helpers.sh
. "$SCRIPT_DIR/lib/iap-helpers.sh"
# tailnet_ssh_failure / tailnet_peer_state -- what the host preflight tells the
# operator when the Air cannot be used.
# shellcheck source=lib/tailnet-helpers.sh
. "$SCRIPT_DIR/lib/tailnet-helpers.sh"
# mac_sign_decision for the preflight, mac_handback_check for the pulled
# binaries. The pin is THIS checkout's: it is what the sync ships to the Air.
# Read by the sourced lib (mac_pinned_sha1), which shellcheck does not follow
# when run from the repo root, so it reports the variable as unused.
# shellcheck disable=SC2034
MAC_SIGNING_PIN_FILE="$REPO_DIR/scripts/mac-signing-identity.sha1"
# shellcheck source=lib/mac-signing.sh
. "$SCRIPT_DIR/lib/mac-signing.sh"

RUNID="$(date +%Y%m%d-%H%M%S)"
# $STAGE_DIR and $ARTIFACTS_DIR are created after the preflight, which needs
# neither: a preflight that fails, or is all that was asked for, leaves no
# directory behind.

# Key-based NON-INTERACTIVE auth. BatchMode=yes makes a missing/rejected key
# fail fast (exit 255) instead of dropping to an interactive Password: prompt
# (which reads /dev/tty, bypassing log redirects, and hangs a background
# release forever). An ARRAY so a space in $MAC_KEY/$HOME survives; expand as
# "${SSH_OPTS[@]}" everywhere.
SSH_OPTS=(-i "$MAC_KEY" -o IdentitiesOnly=yes -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 -o ServerAliveInterval=30 -o ServerAliveCountMax=10)

# Working tree via tar + scp (rsync isn't on every macOS; tar/scp ship with
# OpenSSH). What goes in the tarball is decided by lib/src-sync.sh, shared with
# the linux leg -- this file used to carry its own byte-identical copy of a
# hand-written exclude array, which is how ONE bug (top-level-only anchoring,
# 11.6 GB shipped on 2026-08-31) lived in two places at once. Remote target/ is
# PRESERVED across syncs -- xtask resolves the oam binary repo-relative, and the
# warm cargo cache is the difference between a ~30-min cold build and a
# minutes-long incremental one.

sync_src(){  # sync_src <user@host>
  ok "sync source -> $1:$REMOTE_DIR (remote target/ preserved)"
  # Explicit `|| return 1` per step: this runs inside build_mac, which is
  # invoked as `build_mac || handler` -- bash suppresses errexit in that whole
  # call tree, so without the returns a failed scp would still run the remote
  # extract against a stale/absent tarball. Note this leg must NOT call fail():
  # that exits the script outright and would jump straight past the handler.
  # Hence `warn` then `return 1` -- loud, but still the caller's decision.
  local t; t="$(mktemp "$STAGE_DIR/src-XXXXXX.tar.gz")" || return 1
  write_src_tarball "$REPO_DIR" "$t" \
    || { warn "could not pack the source tree from $REPO_DIR -- is git healthy here? ('git ls-files' must work)"; return 1; }

  # Weigh it BEFORE pushing it -- see the linux leg for the incident.
  local bytes; bytes="$(wc -c <"$t" 2>/dev/null | tr -dc '0-9')"
  if src_tarball_over_ceiling "$bytes"; then
    warn "biggest paths the sync would ship:"
    src_largest_paths "$REPO_DIR" 10 >&2 || true
    warn "source tarball is $((bytes / 1048576))MB, over the ${OAM_SRC_TARBALL_MAX_MB}MB ceiling -- something is shipping build output. Check the paths above, then either clean them up or raise OAM_SRC_TARBALL_MAX_MB if the growth is legitimate."
    return 1
  fi
  ok "source tarball: $((bytes / 1024))KB (ceiling ${OAM_SRC_TARBALL_MAX_MB}MB)"

  scp "${SSH_OPTS[@]}" -q "$t" "$1:oam-src.tar.gz" || { warn "scp of the source tarball to $1 failed"; return 1; }
  ssh "${SSH_OPTS[@]}" "$1" "mkdir -p $REMOTE_DIR && cd $REMOTE_DIR && find . -mindepth 1 -maxdepth 1 ! -name target -exec rm -rf {} + && tar xzf ~/oam-src.tar.gz && rm -f ~/oam-src.tar.gz" \
    || { warn "remote extract of the source tarball into $REMOTE_DIR on $1 failed"; return 1; }
  rm -f "$t"
}

pull(){  # pull <user@host> <remote-glob-under-REMOTE_DIR> <local-dir>
  scp "${SSH_OPTS[@]}" -q "$1:$REMOTE_DIR/$2" "$3"
}

# mac_free_gb <user@host>  -- whole GB free on the volume holding $REMOTE_DIR.
# POSIX `df -Pk` has the same columns on macOS and Linux. An ssh or df failure,
# or a line whose Available column is not a number, prints nothing, which
# disk_needs_reclaim / disk_below_floor read as "not low" -- never as 0GB free.
mac_free_gb(){
  ssh "${SSH_OPTS[@]}" "$1" "df -Pk $REMOTE_DIR | tail -1" 2>/dev/null | awk '$4 ~ /^[0-9]+$/ { print int($4 / 1048576) }'
}

# mac_reclaim <user@host>  -- scripts/gc-target.sh on the Air, via the same
# `build-remote.sh gc` dispatch the linux leg uses.
mac_reclaim(){
  ssh "${SSH_OPTS[@]}" "$1" "cd $REMOTE_DIR && bash scripts/build-remote.sh gc"
}

# --- preflight ----------------------------------------------------------------
if [ "$PREFLIGHT_ONLY" = "1" ]; then
  step "Mac build host preflight -- $MAC_USER@$MAC_HOST"
else
  step "Run $RUNID -- oam mac --mode=$MODE on $MAC_USER@$MAC_HOST"
fi
[ -f "$MAC_KEY" ] || fail "Mac SSH key not found: $MAC_KEY\n  One-time setup:\n    ssh-keygen -t ed25519 -N '' -C oam-mac-air -f \"$MAC_KEY\"\n    ssh-copy-id -i \"$MAC_KEY.pub\" $MAC_USER@$MAC_HOST\n  Already have a key on the Air? point at it with OAM_MAC_KEY=/path/to/key"
# Nothing ships on a preflight-only call, and its caller has its own tree check.
if [ "$PREFLIGHT_ONLY" != "1" ]; then
  ( cd "$REPO_DIR" && git diff --quiet HEAD ) || warn "working tree dirty -- uncommitted changes WILL ship"
fi
ok "target: mac=$MAC_USER@$MAC_HOST (key: $MAC_KEY)"

# How the release leg will sign, decided from the knobs and the committed pin
# BEFORE anything touches the network: a bootstrap release under
# OAM_SIGN_REQUIRED=1, or a malformed pin, is this checkout's problem, not the
# Air's. The Air reaches the same decision from the same inputs.
MAC_SIGN_DECISION=""
if [ "$MODE" = "release" ]; then
  MAC_SIGN_DECISION="$(mac_sign_decision)"
  case "$MAC_SIGN_DECISION" in
    skip:*)     warn "${MAC_SIGN_DECISION#skip:}" ;;
    adhoc:*)    warn "${MAC_SIGN_DECISION#adhoc:}" ;;
    identity:*) ok "mac signing: the pinned identity ${MAC_SIGN_DECISION#identity:}" ;;
    fail:*)     fail "mac signing: ${MAC_SIGN_DECISION#fail:}" ;;
    *)          fail "mac_sign_decision returned '$MAC_SIGN_DECISION' -- refusing to guess how the mac leg signs" ;;
  esac
fi

# mac_tailnet_note  -- what this box's tailnet says about $MAC_HOST, as a
# "\n  ..." continuation for a failure message. Prints nothing when that adds
# nothing: no tailscale CLI here, or the Air is listed and not marked offline.
#
# Everything it prints reaches the operator through fail(), which is `echo -e`:
# text captured from a tool has its backslashes doubled first, so a Windows
# path in it is not read as an escape (`\t`) or a cut-off (`\c`).
mac_tailnet_note(){
  command -v tailscale >/dev/null 2>&1 || return 0
  local st line rows
  # stderr too: that is where a CLI that cannot reach its daemon says so. The
  # helpers take only address-led lines as rows, so a warning is not a device.
  st="$(tailscale status 2>&1)" || {
    line="$(last_nonblank_line "$st")" || line="it printed nothing"
    printf '\n  tailscale status fails on this box (%s) -- is Tailscale running and signed in here?' "${line//\\/\\\\}"
    return 0
  }
  case "$(tailnet_peer_state "$MAC_HOST" "$st")" in
    absent)
      rows="$(tailnet_peer_rows "$st")"
      rows="${rows//\\/\\\\}"
      if [ -z "$rows" ]; then
        printf "\n  'tailscale status' on this box lists no device at '%s', and no other device at all: this box is alone on its tailnet." "$MAC_HOST"
        printf "\n  A 100.x address or MagicDNS name is valid on ONE tailnet, so this box and the Air are on different ones (or the Air is not signed in to Tailscale). Put them on the same one -- 'tailscale switch --list' or 'tailscale login' here, or sign the Air in to this one -- then set OAM_MAC_HOST to what 'tailscale status' shows for the Air."
      else
        printf "\n  'tailscale status' on this box lists no device at '%s'. It lists:\n      %s" "$MAC_HOST" "${rows//$'\n'/$'\n      '}"
        printf "\n  If one of these is the Air, set OAM_MAC_HOST to its address or name: a device that joins a tailnet again gets a new address. If none is, this box and the Air are on different tailnets -- put them on the same one ('tailscale switch --list' or 'tailscale login' here, or sign the Air in to this one)."
      fi ;;
    offline)
      printf "\n  'tailscale status' lists '%s' as offline -- wake the Air, and check Tailscale is connected on it." "$MAC_HOST" ;;
  esac
  return 0
}

# Host preflight: ONE BatchMode ssh, which answers everything a build needs of
# the Air through the resolver and the route every later scp uses -- the name
# resolves, the host answers, the key is enrolled (the key FILE existing proves
# nothing). A separate DNS lookup used to run first and got both halves wrong:
# see lib/tailnet-helpers.sh. ConnectTimeout bounds a dead address at 15s.
probe_out=$(ssh "${SSH_OPTS[@]}" "$MAC_USER@$MAC_HOST" true 2>&1) || {
  probe_rc=$?
  # Backslashes doubled for fail()'s `echo -e` -- see mac_tailnet_note.
  probe_out="${probe_out//\\/\\\\}"
  # An ssh that fails and says nothing (LogLevel QUIET, a killed ssh) must not
  # leave a blank where the cause belongs -- see last_nonblank_line.
  probe_line="$(last_nonblank_line "$probe_out")" \
    || { probe_line="ssh exited $probe_rc and printed nothing"; probe_out="$probe_line"; }
  # ssh's whole output, every line indented to sit under the headline.
  probe_all="${probe_out//$'\r'/}"
  probe_all="${probe_all//$'\n'/$'\n    '}"
  case "$(tailnet_ssh_failure "$probe_out")" in
    auth)
      fail "$MAC_USER@$MAC_HOST answered and refused key authentication with $MAC_KEY:\n    $probe_all\n  Key not enrolled for that account?  ssh-copy-id -i \"$MAC_KEY.pub\" $MAC_USER@$MAC_HOST\n  Otherwise: check OAM_MAC_USER is the account on the Air and is allowed under Remote Login, and that $MAC_KEY is a private key with no passphrase (BatchMode cannot prompt)." ;;
    hostkey)
      probe_offending="$(grep -m1 'Offending' <<<"${probe_out//$'\r'/}" || true)"
      fail "$MAC_HOST answered with a different SSH host key than the one this box recorded for it -- another machine holds that address now, or the Air's host keys were regenerated.${probe_offending:+\n    $probe_offending}\n  If that is expected, drop the stale entry:  ssh-keygen -R $MAC_HOST" ;;
    resolve)
      fail "OAM_MAC_HOST '$MAC_HOST' does not resolve on this box:\n    $probe_line$(mac_tailnet_note)\n  OAM_MAC_HOST has to be the address (first column) or the name (second column) that 'tailscale status' on this box shows for the Air; the address needs no DNS." ;;
    unreachable)
      fail "nothing answered at $MAC_HOST on tcp:22:\n    $probe_line$(mac_tailnet_note)\n  The Air has to be awake and on this box's tailnet, the tailnet's ACLs have to let this box reach its tcp:22 (a denied connection is dropped silently, so it times out), and Remote Login has to be on." ;;
    refused)
      fail "$MAC_HOST is up but nothing is listening on tcp:22:\n    $probe_line\n  Turn on Remote Login on the Air (System Settings > General > Sharing)." ;;
    *)
      fail "ssh to $MAC_USER@$MAC_HOST failed (exit $probe_rc):\n    $probe_all\n  For the detail, run it by hand:  ssh -v -i \"$MAC_KEY\" -o BatchMode=yes $MAC_USER@$MAC_HOST true" ;;
  esac
}
ok "key auth OK on $MAC_USER@$MAC_HOST"

# A pinned identity must be usable from an ssh session on the Air NOW, before
# release-local.sh tags. Preflight syncs nothing, so the Air's copy of the
# provision script may be a release old: THIS checkout's copy is piped to
# `bash -s` instead (the script is written to survive that -- see its header).
# `--check` unlocks the dedicated keychain, matches the certificate to the one
# the Air recorded and makes a real probe signature; its stdout (keychain= and
# sha1=) is captured, never passed through, so the stdout-silent contract holds.
# Ad-hoc needs no keychain and skip needs nothing, so neither asks the Air.
case "$MAC_SIGN_DECISION" in
  identity:*)
    mac_pin="${MAC_SIGN_DECISION#identity:}"
    mac_check_out="$(ssh "${SSH_OPTS[@]}" "$MAC_USER@$MAC_HOST" 'bash -s -- --check' \
      < "$SCRIPT_DIR/provision-mac-signing.sh")" \
      || fail "the pinned mac signing identity $mac_pin is not usable on $MAC_USER@$MAC_HOST -- provision-mac-signing.sh --check said why, above.\n  First-time setup:  ssh <air> 'bash -s -- --generate' < scripts/provision-mac-signing.sh\n  Replacement Air:   ssh <air> 'bash -s -- --import <p12> <password-file>' < scripts/provision-mac-signing.sh\n  To ship without signing on purpose: OAM_SKIP_MAC_SIGN=1"
    mac_have="$(printf '%s\n' "$mac_check_out" | sed -n 's/^sha1=//p' | head -n 1)"
    [ "$mac_have" = "$mac_pin" ] \
      || fail "the Air signs with certificate '${mac_have:-<none reported>}' but this checkout pins $mac_pin (scripts/mac-signing-identity.sha1). Restore the pinned identity on the Air (provision-mac-signing.sh --import), or update the pin in a change that says why"
    ok "mac signing identity $mac_pin is usable on $MAC_USER@$MAC_HOST"
    ;;
esac

if [ "$PREFLIGHT_ONLY" = "1" ]; then
  exit 0
fi

STAGE_DIR="$(mktemp -d -t oam-tailnet-build-$RUNID-XXXXXX)"
ARTIFACTS_DIR="$STAGE_DIR/artifacts"
HANDBACK_DIR="$STAGE_DIR/handback"
mkdir -p "$STAGE_DIR/logs" "$ARTIFACTS_DIR"

# --- build --------------------------------------------------------------------
# Called as `build_mac || handler` -- every step fails the function EXPLICITLY
# (bash suppresses set -e inside the || call tree).
build_mac(){
  local hp="$MAC_USER@$MAC_HOST" free
  sync_src "$hp" || return 1
  # Disk headroom, reclaimed the way the linux leg does it -- after the sync, so
  # the gc dispatch is this run's (see the ordering comment there). This leg
  # used to never prune: target/ on the Air reached 93GB and the disk 91% full
  # (2026-09-25), with superseded cargo output from every release since August.
  free="$(mac_free_gb "$hp")"
  if disk_needs_reclaim "$free"; then
    warn "mac has ${free}GB free -- reclaiming accreted cargo output before building"
    mac_reclaim "$hp" || warn "pre-build reclaim failed -- continuing to the threshold check"
    free="$(mac_free_gb "$hp")"
  fi
  if disk_below_floor "$free"; then
    warn "mac still has only ${free}GB free after reclaiming prunable cargo output -- a build needs ~7GB. Free space on the Air outside ~/${REMOTE_DIR}/target."
    return 1
  fi
  if [ -n "$free" ]; then ok "mac disk headroom: ${free}GB free"
  else warn "could not read free disk on the Air -- headroom check skipped"; fi
  case "$MODE" in
    release)
      # The knobs were validated as 0|1 at the top: nothing else reaches this
      # remote command line.
      ssh "${SSH_OPTS[@]}" "$hp" "cd $REMOTE_DIR && OAM_SKIP_MAC_X64=$SKIP_MAC_X64 OAM_SIGN_REQUIRED=$SIGN_REQUIRED OAM_SKIP_MAC_SIGN=$SKIP_MAC_SIGN bash scripts/build-remote.sh mac-release" || return 1
      pull "$hp" "dist/oam-aarch64-apple-darwin" "$ARTIFACTS_DIR/" || return 1
      if [ "$SKIP_MAC_X64" != "1" ]; then
        pull "$hp" "dist/oam-x86_64-apple-darwin" "$ARTIFACTS_DIR/" || return 1
      fi
      # Beside ARTIFACTS_DIR, never in it: release-local.sh copies binaries out
      # of there, and the hand-back is not an asset.
      mkdir -p "$HANDBACK_DIR" || return 1
      pull "$hp" "dist/mac-sha256.txt" "$HANDBACK_DIR/" || return 1
      ;;
    measure)
      ssh "${SSH_OPTS[@]}" "$hp" "cd $REMOTE_DIR && bash scripts/build-remote.sh mac-measure" || return 1
      mkdir -p "$ARTIFACTS_DIR/mac-arm64" || return 1
      pull "$hp" "conformance/scorecard.json"            "$ARTIFACTS_DIR/mac-arm64/" || return 1
      pull "$hp" "conformance/node-suite-scorecard.json" "$ARTIFACTS_DIR/mac-arm64/" || return 1
      pull "$hp" "CONFORMANCE.md"                        "$ARTIFACTS_DIR/mac-arm64/" || return 1
      pull "$hp" "CONFORMANCE-NODE.md"                   "$ARTIFACTS_DIR/mac-arm64/" || return 1
      ;;
    bench)
      ssh "${SSH_OPTS[@]}" "$hp" "cd $REMOTE_DIR && bash scripts/build-remote.sh mac-bench" || return 1
      mkdir -p "$ARTIFACTS_DIR/mac-arm64" || return 1
      pull "$hp" "BENCHMARKS.md"      "$ARTIFACTS_DIR/mac-arm64/" || return 1
      pull "$hp" "bench/results.json" "$ARTIFACTS_DIR/mac-arm64/" || return 1
      ;;
    surface-gaps)
      ssh "${SSH_OPTS[@]}" "$hp" "cd $REMOTE_DIR && bash scripts/build-remote.sh surface-gaps" || return 1
      # The WHOLE ratchet file comes back, not a darwin fragment. The generator
      # merges: it rewrites only platforms[darwin] and leaves the win32/linux
      # sections exactly as they arrived in the sync. So the pulled file is
      # "what we sent, with darwin re-measured", which is safe to overwrite the
      # local copy with -- and is why these legs have to run one at a time,
      # each starting from the previous one's output.
      pull "$hp" "conformance/surface-gaps.json" "$REPO_DIR/conformance/" || return 1
      ;;
  esac
  # Reclaim AFTER this mode's outputs are pulled, every run, so target/ never
  # accretes until the check above has to act. Advisory: the leg has already
  # succeeded, and a failed cleanup must not retract that.
  mac_reclaim "$hp" || warn "post-build reclaim failed (non-blocking -- outputs are already pulled)"
}

step "Run mac --mode=$MODE on $MAC_USER@$MAC_HOST"
build_mac > "$STAGE_DIR/logs/mac.log" 2>&1 \
  || { tail -30 "$STAGE_DIR/logs/mac.log" >&2; fail "mac leg failed -- see $STAGE_DIR/logs/mac.log"; }
ok "mac leg ok"

# --- verify -------------------------------------------------------------------
step "Verify staged artifacts"
find "$ARTIFACTS_DIR" -type f -exec ls -lh {} \; >&2
case "$MODE" in
  release)
    [ -f "$ARTIFACTS_DIR/oam-aarch64-apple-darwin" ] || fail "no mac-arm64 binary staged"
    if [ "$SKIP_MAC_X64" != "1" ]; then
      [ -f "$ARTIFACTS_DIR/oam-x86_64-apple-darwin" ] || fail "no mac-x64 binary staged"
    fi
    # The pulled bytes must be the ones the Air signed, verified and JIT-smoked.
    mac_names=(oam-aarch64-apple-darwin)
    [ "$SKIP_MAC_X64" = "1" ] || mac_names+=(oam-x86_64-apple-darwin)
    mac_handback_check "$HANDBACK_DIR/mac-sha256.txt" "$ARTIFACTS_DIR" "${mac_names[@]}" \
      || fail "the pulled mac binaries do not match the Air's hand-back hashes -- see above"
    ok "pulled mac binaries match the Air's hand-back hashes"
    ;;
  measure) [ -f "$ARTIFACTS_DIR/mac-arm64/node-suite-scorecard.json" ] || fail "no scorecard staged" ;;
  bench)   [ -f "$ARTIFACTS_DIR/mac-arm64/results.json" ] || fail "no bench results staged" ;;
  surface-gaps)
    # Lands in the repo, not the staging dir -- assert darwin actually moved,
    # since a silently-unchanged section is the failure this mode exists to
    # prevent (the gate would then be measuring a host that never ran).
    node -e '
      const g = require(process.argv[1]);
      const d = g.platforms && g.platforms.darwin;
      if (!d) { console.error("no darwin section in the pulled ratchet"); process.exit(1); }
      console.error(`darwin: ${d.counts.present}/${d.counts.nodeExportNames} present, generated against ${d.generatedAgainst}`);
    ' "$REPO_DIR/conformance/surface-gaps.json" || fail "pulled ratchet has no darwin section"
    ;;
esac
ok "all required artifacts staged under $ARTIFACTS_DIR"

# LAST stdout line = the artifact dir, for ART=$(...) capture.
echo "$ARTIFACTS_DIR"
