#!/bin/bash
# =============================================================================
# Runs ON a remote build host (shipped in with the repo tree by
# build-platforms-gcp-iap.sh / build-platforms-tailnet.sh). Recreates the
# per-platform jobs of the deleted GitHub workflows (ci.yml, release.yml,
# node-compat.yml, bench.yml) for whatever platform this host is. Kept as a
# real script (not inline ssh strings) so it can use functions and case
# without SSH quoting hell.
#
# Usage (invoked remotely):  bash scripts/build-remote.sh <dispatch>
#   <dispatch>:
#     prep         -- toolchain guard + one-time install: rustup (auto-installs
#                     if missing), toolchain per rust-toolchain.toml, cc/node
#                     presence checks, tsgo best-effort (ci.yml parity:
#                     continue-on-error). Run ONCE per synced tree; the
#                     sub-steps below never re-prep.
#     gate         -- cargo fmt --check + clippy -D warnings   (ci.yml parity)
#     test         -- cargo build --workspace + cargo test --workspace
#                     (15-min ceiling where `timeout` exists) + debug smoke
#     surface-gaps -- node scripts/gen-surface-gaps.mjs (records THIS host's
#                     section of the builtin export-parity ratchet)
#     conformance  -- cargo run -p xtask -- conformance  (node-differential
#                     gate; needs node on PATH)
#     node-suite   -- cargo run -p xtask -- node-suite   (ratchet + scorecard)
#     build        -- release build for the HOST triple -> dist/oam-<triple>
#                     + release-binary smoke
#     bench        -- cargo run -p xtask -- bench --release --compare
#                     (node required for the comparison columns; missing bun
#                     just drops that column -- best-effort install attempted)
#     io-uring-ab  -- Linux-only same-binary A/B (bench.yml io-uring-ab parity)
#     mac-release  -- one-shot mac release leg (tailnet SSH has no idle-drop,
#                     so no sub-step splitting needed): prep + gate + test +
#                     build (arm64 native) + x64 build via the
#                     x86_64-apple-darwin HOST toolchain under Rosetta 2.
#                     OAM_SKIP_MAC_X64=1 drops the x64 leg.
#     mac-measure  -- one-shot: prep + conformance + node-suite (both
#                     advisory: a tripped gate warns, scorecards still land)
#     mac-bench    -- one-shot: prep + bench
#
# Why the x64-under-emulation leg works: crates/oam_engine/build.rs refuses
# cross-compilation (the V8 startup snapshot must be generated by a process
# of the TARGET architecture). Running the x86_64 HOST toolchain under
# Rosetta 2 (mac) / Windows-on-ARM x64 emulation (win) makes the build script
# a genuinely-x64 process, so host arch == target arch and the snapshot is
# correct by construction. Slower than native, but it is the only way to ship
# the x64 targets without dedicated x64 hardware.
#
# Cache layout: everything stays repo-relative (xtask resolves the oam binary
# at `<repo>/target/<profile>/oam` and self-builds there, ignoring
# CARGO_TARGET_DIR -- see xtask/src/conformance.rs). The orchestrators
# preserve `target/` across source syncs so deps + the rusty_v8 static lib
# survive; only workspace crates rebuild. The x64-emulation leg is the one
# exception: it isolates into target/x64-host so its (x64) host artifacts
# never churn the native toolchain's fingerprints.
# =============================================================================
set -euo pipefail

DISPATCH="${1:?dispatch: prep | gate | test | conformance | surface-gaps | node-suite | build | bench | io-uring-ab | mac-release | mac-measure | mac-bench}"

# Non-interactive ssh does not source ~/.profile, and rustup installs into
# ~/.cargo -- pull its env in explicitly so every dispatch finds cargo.
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
# tsgo lives in a user npm prefix (see remote_prep) -- same reasoning.
export PATH="$HOME/.npm-oam/bin:$PATH"

note(){ echo "[remote] $*"; }
warn(){ echo "[remote] WARN: $*" >&2; }
die(){  echo "[remote] FATAL: $*" >&2; exit 1; }

# --- shared helpers ----------------------------------------------------------

host_triple(){ rustc -vV | awk '/^host:/ {print $2}'; }

# with_timeout <secs> <cmd...>: GNU timeout (Linux) or brew-coreutils gtimeout
# (mac) when present; otherwise runs unbounded. Callers that care about the
# unbounded case warn separately.
with_timeout() {
  local secs="$1"; shift
  if command -v timeout >/dev/null 2>&1; then timeout "$secs" "$@"
  elif command -v gtimeout >/dev/null 2>&1; then gtimeout "$secs" "$@"
  else "$@"; fi
}

# smoke <oam-binary>: ci.yml's smoke step, byte-for-byte assertion.
smoke() {
  local bin="$1" d out
  d="$(mktemp -d)"
  echo "console.log('ci smoke', 6 * 7)" > "$d/smoke.js"
  # Guarded capture: under set -e a crash inside $() would kill the script
  # with no diagnostic and leak $d. 5-min ceiling = ci.yml's
  # timeout-minutes: 5 on the smoke step (a hung runtime must die, not
  # wedge the whole leg).
  if ! out="$(with_timeout 300 "$bin" run "$d/smoke.js")"; then
    rm -rf "$d"
    die "smoke run failed (crash or 5-min hang) for $bin"
  fi
  rm -rf "$d"
  [ "$out" = "ci smoke 42" ] || die "smoke output unexpected from $bin: '$out'"
  note "smoke ok ($bin)"
}

remote_prep() {
  # rustup auto-install: first run on a freshly-imaged host. `--default-
  # toolchain none` because the real toolchain comes from rust-toolchain.toml
  # in the next step (channel + rustfmt/clippy components).
  if ! command -v cargo >/dev/null 2>&1; then
    note "rustup not found -- installing (one-time)"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
      | sh -s -- -y --profile minimal --default-toolchain none
    . "$HOME/.cargo/env"
  fi
  # Reads rust-toolchain.toml (cwd = repo root); same step ci.yml ran.
  rustup toolchain install
  note "toolchain: $(rustc --version) ($(host_triple))"

  # Rust needs a system linker driver. The yaw builder image ships
  # build-essential; a fresh image without it fails here with the fix named.
  command -v cc >/dev/null 2>&1 || command -v clang >/dev/null 2>&1 \
    || die "no C compiler/linker driver (cc/clang). On Ubuntu: sudo apt-get install -y build-essential"

  # node: required by conformance (differential oracle), node-suite, and the
  # bench comparison columns. Warn here, hard-fail in the dispatches that
  # actually need it -- a build-only run must not require node.
  if command -v node >/dev/null 2>&1; then
    note "node $(node --version) on PATH"
  else
    warn "node not on PATH -- conformance/node-suite/bench dispatches will fail"
  fi

  # tsgo for the `oam check` tests: ci.yml ran this continue-on-error, so
  # best-effort here too. A USER prefix, not npm's system prefix: stock
  # Ubuntu has prefix=/usr and `npm install -g` EACCESes there (observed on
  # the GCP builder -- the failure was silent and the oam-check e2e test
  # then failed instead of skipping). PATH for it is exported at the top of
  # this script so every later dispatch finds tsgo.
  if command -v tsgo >/dev/null 2>&1; then
    note "tsgo already on PATH"
  elif command -v npm >/dev/null 2>&1; then
    npm install -g --prefix "$HOME/.npm-oam" @typescript/native-preview >/dev/null 2>&1 \
      && note "tsgo installed ($HOME/.npm-oam/bin)" \
      || warn "tsgo install failed (non-blocking; oam-check e2e coverage degrades without it)"
  fi
  note "prep complete"
}

run_gate() {
  cargo fmt --all --check
  # -D warnings via clippy args, NOT RUSTFLAGS: a global RUSTFLAGS would
  # fingerprint-poison the cargo cache against the plain build/test steps.
  cargo clippy --workspace --all-targets -- -D warnings
  note "gate ok (fmt + clippy)"
}

run_test() {
  cargo build --workspace
  # ci.yml bounded a hung test at 15 min (deadlocked/lingering test class).
  command -v timeout >/dev/null 2>&1 || command -v gtimeout >/dev/null 2>&1 \
    || warn "no timeout/gtimeout on this host -- a deadlocked test hangs instead of dying at 15 min (mac: brew install coreutils)"
  with_timeout 900 cargo test --workspace
  smoke "target/debug/oam"
}

run_conformance() {
  command -v node >/dev/null 2>&1 || die "conformance needs node on PATH (differential oracle)"
  cargo run -p xtask -- conformance
}

# Record THIS host's section of the builtin export-parity ratchet.
#
# The ratchet is per-platform because node's own builtin surface is (WSA*
# errnos on Windows, getuid/setgid on POSIX), and the generator merges -- it
# rewrites only platforms[process.platform] and leaves the other hosts'
# sections alone. So the flow is: run this on each host, pull the file back,
# and the accumulated result covers every platform the gate runs on.
# Until a host has a section the gate MEASURES but does not GATE there.
run_surface_gaps() {
  command -v node >/dev/null 2>&1 || die "surface-gaps needs node on PATH (parity oracle)"
  # The generator shells out to `cargo build` before probing; without this the
  # failure surfaces as a bare "cargo: not found" from inside a Node script.
  command -v cargo >/dev/null 2>&1 || die "surface-gaps needs cargo on PATH (run the prep dispatch first)"
  node scripts/gen-surface-gaps.mjs
}

run_node_suite() {
  command -v node >/dev/null 2>&1 || die "node-suite needs node on PATH"
  cargo run -p xtask -- node-suite
}

build_host_release() {
  local triple ext=""
  triple="$(host_triple)"
  case "$triple" in *windows*) ext=".exe" ;; esac
  cargo build --release -p oam_cli
  mkdir -p dist
  cp "target/release/oam${ext}" "dist/oam-${triple}${ext}"
  smoke "dist/oam-${triple}${ext}"
  note "staged dist/oam-${triple}${ext}"
}

# mac only: x86_64-apple-darwin leg on an Apple-Silicon host, via the x64
# HOST toolchain under Rosetta 2 (see header). The binary smokes under
# Rosetta too, which proves both the executable and its embedded snapshot.
build_mac_x64() {
  /usr/bin/arch -x86_64 /usr/bin/true 2>/dev/null \
    || die "Rosetta 2 not installed -- run: softwareupdate --install-rosetta --agree-to-license  (or set OAM_SKIP_MAC_X64=1 to drop the mac-x64 asset)"
  # --force-non-host: rustup refuses a foreign-host toolchain without it.
  rustup toolchain install stable-x86_64-apple-darwin --profile minimal --force-non-host
  CARGO_TARGET_DIR=target/x64-host \
    cargo +stable-x86_64-apple-darwin build --release --target x86_64-apple-darwin -p oam_cli
  mkdir -p dist
  cp "target/x64-host/x86_64-apple-darwin/release/oam" "dist/oam-x86_64-apple-darwin"
  smoke "dist/oam-x86_64-apple-darwin"
  note "staged dist/oam-x86_64-apple-darwin (built under Rosetta 2)"
}

run_bench() {
  command -v node >/dev/null 2>&1 || die "bench --compare needs node on PATH"
  # bun is optional (a missing bun just drops that column) -- try the official
  # installer once, non-blocking, matching bench.yml's install step.
  if ! command -v bun >/dev/null 2>&1; then
    export PATH="$HOME/.bun/bin:$PATH"
    if ! command -v bun >/dev/null 2>&1; then
      warn "bun not on PATH -- attempting install (non-blocking)"
      (curl -fsSL https://bun.sh/install | bash) >/dev/null 2>&1 \
        || warn "bun install failed -- bench runs without the bun column"
    fi
  fi
  node --version || true
  bun --version 2>/dev/null || true
  cargo run -p xtask -- bench --release --compare
}

run_io_uring_ab() {
  [ "$(uname -s)" = "Linux" ] || die "io-uring-ab is Linux-only"
  cargo build --release -p oam_cli
  echo "## baseline (io_uring off):"
  for _ in 1 2; do ./target/release/oam run bench/io_uring_ab.mjs --no-check; done
  echo "## io_uring on (OAM_IO_URING=1):"
  for _ in 1 2; do OAM_IO_URING=1 ./target/release/oam run bench/io_uring_ab.mjs --no-check; done
}

# --- dispatch ----------------------------------------------------------------

case "$DISPATCH" in
  prep)         remote_prep ;;
  gate)         run_gate ;;
  test)         run_test ;;
  conformance)  run_conformance ;;
  surface-gaps) run_surface_gaps ;;
  node-suite)   run_node_suite ;;
  build)        build_host_release ;;
  bench)        run_bench ;;
  io-uring-ab)  run_io_uring_ab ;;
  mac-release)
    remote_prep
    run_gate
    run_test
    # Conformance on the mac leg too, not just the Linux one. run_gate is
    # fmt+clippy only, so without this the differential corpus and the builtin
    # export-parity gate never execute on darwin -- and darwin-only native
    # code (fs statfs uses a DIFFERENT struct layout from linux) would ship
    # compile-checked but never run.
    run_conformance
    build_host_release
    if [ "${OAM_SKIP_MAC_X64:-0}" = "1" ]; then
      warn "OAM_SKIP_MAC_X64=1 -- mac-x64 asset dropped this run"
    else
      build_mac_x64
    fi
    ;;
  mac-measure)
    # node-compat.yml measure parity (continue-on-error): a tripped gate must
    # not discard the scorecard it just wrote -- the scorecard IS the product
    # here. xtask writes the scorecard before exiting non-zero on divergence /
    # ratchet violation, so the orchestrator's pull still gets fresh numbers.
    remote_prep
    run_conformance || warn "conformance diverged (advisory in measure mode)"
    run_node_suite  || warn "node-suite gate tripped (advisory in measure mode)"
    ;;
  mac-bench)
    remote_prep
    run_bench
    ;;
  *) die "unknown dispatch: $DISPATCH" ;;
esac

note "$DISPATCH complete"
