#!/bin/bash
# =============================================================================
# Runs ON a remote build host (shipped in with the repo tree by
# build-platforms-gcp-iap.sh / build-platforms-tailnet.sh). Recreates the
# per-platform jobs of the deleted GitHub workflows (ci.yml, release.yml,
# node-compat.yml, bench.yml) for whatever platform this host is. Kept as a
# real script (not inline ssh strings) so it can use functions and case
# without SSH quoting hell.
#
# Usage (invoked remotely):  bash scripts/build-remote.sh <dispatch>
#   <dispatch>:
#     prep         -- toolchain guard + one-time install: rustup (auto-installs
#                     if missing), toolchain per rust-toolchain.toml, cc
#                     presence check, the pinned Node oracle (best-effort
#                     here -- see "Pinned Node" below), tsgo best-effort
#                     (ci.yml parity: continue-on-error). Run ONCE per synced
#                     tree; the sub-steps below never re-prep.
#     gate         -- cargo fmt --check + clippy -D warnings   (ci.yml parity)
#     test         -- cargo build --workspace + cargo test --workspace
#                     (15-min ceiling where `timeout` exists) + debug smoke
#     surface-gaps -- node scripts/gen-surface-gaps.mjs (records THIS host's
#                     section of the builtin export-parity ratchet; pinned
#                     node)
#     conformance  -- cargo run -p xtask -- conformance  (node-differential
#                     gate; pinned node)
#     node-suite   -- cargo run -p xtask -- node-suite   (ratchet + scorecard;
#                     runs no node -- its oracle is each test's exit code)
#     build        -- release build for the HOST triple -> dist/oam-<triple>
#                     + release-binary smoke
#     bench        -- cargo run -p xtask -- bench --release --compare
#                     (pinned node for the comparison columns; missing bun
#                     just drops that column -- best-effort install attempted)
#     io-uring-ab  -- Linux-only same-binary A/B (bench.yml io-uring-ab parity)
#     gc           -- reclaim accreted cargo output (scripts/gc-target.sh):
#                     incremental/ wholesale + per-family dedupe of deps/.
#                     Deliberately NOT `rm -rf target/debug` -- see run_gc.
#     mac-release  -- one-shot mac release leg (tailnet SSH has no idle-drop,
#                     so no sub-step splitting needed): prep + gate + test +
#                     build (arm64 native) + x64 build via the
#                     x86_64-apple-darwin HOST toolchain under Rosetta 2.
#                     OAM_SKIP_MAC_X64=1 drops the x64 leg.
#     mac-measure  -- one-shot: prep + conformance + node-suite (both
#                     advisory: a tripped gate warns, scorecards still land)
#     mac-bench    -- one-shot: prep + bench
#
# Why the x64-under-emulation leg works: crates/oam_engine/build.rs refuses
# cross-compilation (the V8 startup snapshot must be generated by a process
# of the TARGET architecture). Running the x86_64 HOST toolchain under
# Rosetta 2 (mac) / Windows-on-ARM x64 emulation (win) makes the build script
# a genuinely-x64 process, so host arch == target arch and the snapshot is
# correct by construction. Slower than native, but it is the only way to ship
# the x64 targets without dedicated x64 hardware.
#
# Pinned Node: the oracle dispatches (conformance, surface-gaps, bench) run
# against exactly the Node in .node-version, provisioned from nodejs.org into
# ~/.cache/oam-node/node-v<version>-<platform> (sha256-verified against the
# release's SHASUMS256.txt, cached per version) and put FIRST on PATH -- never
# whatever node the host image or a package manager happens to carry. Fail-
# closed: a host that cannot provision it fails those dispatches with the
# reason. Mechanism and rationale: scripts/lib/node-pin.sh.
# OAM_ALLOW_NODE_MISMATCH=1 (which the orchestrators do NOT forward) downgrades
# that to a warning for a dispatch run by hand on the host.
#
# Cache layout: everything stays repo-relative (xtask resolves the oam binary
# at `<repo>/target/<profile>/oam` and self-builds there, ignoring
# CARGO_TARGET_DIR -- see xtask/src/conformance.rs). The orchestrators
# preserve `target/` across source syncs so deps + the rusty_v8 static lib
# survive; only workspace crates rebuild. The x64-emulation leg is the one
# exception: it isolates into target/x64-host so its (x64) host artifacts
# never churn the native toolchain's fingerprints.
# =============================================================================
set -euo pipefail

DISPATCH="${1:?dispatch: prep | gate | test | conformance | surface-gaps | node-suite | build | bench | io-uring-ab | gc | mac-release | mac-measure | mac-bench}"

# Non-interactive ssh does not source ~/.profile, and rustup installs into
# ~/.cargo -- pull its env in explicitly so every dispatch finds cargo.
[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"
# tsgo lives in a user npm prefix (see remote_prep) -- same reasoning.
export PATH="$HOME/.npm-oam/bin:$PATH"

note(){ echo "[remote] $*"; }
warn(){ echo "[remote] WARN: $*" >&2; }
die(){  echo "[remote] FATAL: $*" >&2; exit 1; }

# --- shared helpers ----------------------------------------------------------

host_triple(){ rustc -vV | awk '/^host:/ {print $2}'; }

# with_timeout <secs> <cmd...>: GNU timeout (Linux) or brew-coreutils gtimeout
# (mac) when present; otherwise runs unbounded. Callers that care about the
# unbounded case warn separately.
with_timeout() {
  local secs="$1"; shift
  if command -v timeout >/dev/null 2>&1; then timeout "$secs" "$@"
  elif command -v gtimeout >/dev/null 2>&1; then gtimeout "$secs" "$@"
  else "$@"; fi
}

# smoke <oam-binary>: ci.yml's smoke step, byte-for-byte assertion.
smoke() {
  local bin="$1" d out
  d="$(mktemp -d)"
  echo "console.log('ci smoke', 6 * 7)" > "$d/smoke.js"
  # Guarded capture: under set -e a crash inside $() would kill the script
  # with no diagnostic and leak $d. 5-min ceiling = ci.yml's
  # timeout-minutes: 5 on the smoke step (a hung runtime must die, not
  # wedge the whole leg).
  if ! out="$(with_timeout 300 "$bin" run "$d/smoke.js")"; then
    rm -rf "$d"
    die "smoke run failed (crash or 5-min hang) for $bin"
  fi
  rm -rf "$d"
  [ "$out" = "ci smoke 42" ] || die "smoke output unexpected from $bin: '$out'"
  note "smoke ok ($bin)"
}

# use_pinned_node: put the pinned Node (.node-version) first on PATH for the
# rest of this shell, provisioning it on first use. Dies unless it can -- the
# value of the oracle is that it is the SAME Node on every leg, so a silent
# fallback to the host's own node is exactly the failure this exists to stop.
#
# The lib is sourced HERE, not at the top: dispatches that never touch node
# (gc above all) must keep working in a tree that carries only this script.
use_pinned_node() {
  local lib="scripts/lib/node-pin.sh"
  [ -f "$lib" ] || die "$lib is missing -- cannot provision the pinned Node oracle (is the cwd the repo root?)"
  # shellcheck source=lib/node-pin.sh
  . "$lib"
  if node_pin_use "."; then
    note "node $(node --version) at $(command -v node) (pinned by .node-version)"
    return 0
  fi
  if [ "${OAM_ALLOW_NODE_MISMATCH:-0}" = "1" ]; then
    warn "pinned Node unavailable (reason above) -- OAM_ALLOW_NODE_MISMATCH=1, continuing with $(command -v node || echo 'NO node') $(node --version 2>/dev/null || true). Receipts from this run do NOT describe the pinned Node."
    return 0
  fi
  die "could not put the pinned Node (.node-version) first on PATH -- reason above. The oracle must be that exact Node on every leg: fix the host (outbound HTTPS to nodejs.org, curl or wget, sha256sum or shasum) rather than fall back to its own node."
}

remote_prep() {
  # rustup auto-install: first run on a freshly-imaged host. `--default-
  # toolchain none` because the real toolchain comes from rust-toolchain.toml
  # in the next step (channel + rustfmt/clippy components).
  if ! command -v cargo >/dev/null 2>&1; then
    note "rustup not found -- installing (one-time)"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs \
      | sh -s -- -y --profile minimal --default-toolchain none
    . "$HOME/.cargo/env"
  fi
  # Reads rust-toolchain.toml (cwd = repo root); same step ci.yml ran.
  rustup toolchain install
  note "toolchain: $(rustc --version) ($(host_triple))"

  # Rust needs a system linker driver. The yaw builder image ships
  # build-essential; a fresh image without it fails here with the fix named.
  command -v cc >/dev/null 2>&1 || command -v clang >/dev/null 2>&1 \
    || die "no C compiler/linker driver (cc/clang). On Ubuntu: sudo apt-get install -y build-essential"

  # node: the oracle dispatches need EXACTLY the pinned version. Provisioned
  # here so the one-time download happens up front with its log in the prep
  # step, but only WARNED on: a build-only run (OAM_LINUX_FAST=1) must not
  # require node at all. The dispatches that need it call use_pinned_node
  # themselves and die there.
  #
  # The host's own node is logged first. It is what these legs used to compare
  # against, and naming it is how a reader sees what the pin replaced.
  if command -v node >/dev/null 2>&1; then
    note "host node: $(node --version) at $(command -v node) (NOT the oracle)"
  else
    note "host node: none on PATH (not needed -- the oracle is provisioned)"
  fi
  # Subshell: prep only proves the pinned Node CAN be provisioned. Its PATH
  # change stays in there, so the tsgo install below keeps using the host's
  # npm exactly as before.
  (
    # shellcheck source=lib/node-pin.sh
    . scripts/lib/node-pin.sh \
      && node_pin_use "." \
      && note "pinned node: $(node --version) at $(command -v node)"
  ) || warn "could not provision the pinned Node (reason above) -- conformance/surface-gaps/bench dispatches will fail"

  # tsgo for the `oam check` tests: ci.yml ran this continue-on-error, so
  # best-effort here too. A USER prefix, not npm's system prefix: stock
  # Ubuntu has prefix=/usr and `npm install -g` EACCESes there (observed on
  # the GCP builder -- the failure was silent and the oam-check e2e test
  # then failed instead of skipping). PATH for it is exported at the top of
  # this script so every later dispatch finds tsgo.
  if command -v tsgo >/dev/null 2>&1; then
    note "tsgo already on PATH"
  elif command -v npm >/dev/null 2>&1; then
    npm install -g --prefix "$HOME/.npm-oam" @typescript/native-preview >/dev/null 2>&1 \
      && note "tsgo installed ($HOME/.npm-oam/bin)" \
      || warn "tsgo install failed (non-blocking; oam-check e2e coverage degrades without it)"
  fi
  note "prep complete"
}

run_gate() {
  cargo fmt --all --check
  # -D warnings via clippy args, NOT RUSTFLAGS: a global RUSTFLAGS would
  # fingerprint-poison the cargo cache against the plain build/test steps.
  cargo clippy --workspace --all-targets -- -D warnings
  note "gate ok (fmt + clippy)"
}

run_test() {
  cargo build --workspace
  # The http_server_wire flood tests dial ~300 sockets at once and the server
  # answers every one, to prove a server no longer stops at 256 connections.
  # A stock POSIX soft limit sits below that (macOS ships 256), so without
  # this the HARNESS runs out of descriptors first and those tests skip
  # themselves. The spawned servers inherit it. Best effort: fall back to the
  # hard limit, and if neither takes, the tests report why they skipped.
  ulimit -n 4096 2>/dev/null || ulimit -n "$(ulimit -Hn)" 2>/dev/null || true
  note "descriptor limit for tests: $(ulimit -n)"
  # ci.yml bounded a hung test at 15 min (deadlocked/lingering test class).
  command -v timeout >/dev/null 2>&1 || command -v gtimeout >/dev/null 2>&1 \
    || warn "no timeout/gtimeout on this host -- a deadlocked test hangs instead of dying at 15 min (mac: brew install coreutils)"
  with_timeout 900 cargo test --workspace
  smoke "target/debug/oam"
}

run_conformance() {
  use_pinned_node
  cargo run -p xtask -- conformance
}

# Record THIS host's section of the builtin export-parity ratchet.
#
# The ratchet is per-platform because node's own builtin surface is (WSA*
# errnos on Windows, getuid/setgid on POSIX), and the generator merges -- it
# rewrites only platforms[process.platform] and leaves the other hosts'
# sections alone. So the flow is: run this on each host, pull the file back,
# and the accumulated result covers every platform the gate runs on.
# Until a host has a section the gate MEASURES but does not GATE there.
run_surface_gaps() {
  use_pinned_node
  # The generator shells out to `cargo build` before probing; without this the
  # failure surfaces as a bare "cargo: not found" from inside a Node script.
  command -v cargo >/dev/null 2>&1 || die "surface-gaps needs cargo on PATH (run the prep dispatch first)"
  node scripts/gen-surface-gaps.mjs
}

# No node here, on purpose. The node-suite's oracle is each vendored test's own
# exit code under oam: xtask never spawns node for it, and no vendored test
# spawns `node` by name (they use process.execPath, which is oam). What ties it
# to the pinned version is the CORPUS -- xtask refuses to run when
# conformance/vendor/node/manifest.json names a different Node than
# .node-version. Requiring node on PATH here only ever added a failure mode.
run_node_suite() {
  cargo run -p xtask -- node-suite
}

build_host_release() {
  local triple ext=""
  triple="$(host_triple)"
  case "$triple" in *windows*) ext=".exe" ;; esac
  cargo build --release -p oam_cli
  mkdir -p dist
  cp "target/release/oam${ext}" "dist/oam-${triple}${ext}"
  smoke "dist/oam-${triple}${ext}"
  note "staged dist/oam-${triple}${ext}"
}

# mac only: x86_64-apple-darwin leg on an Apple-Silicon host, via the x64
# HOST toolchain under Rosetta 2 (see header). The binary smokes under
# Rosetta too, which proves both the executable and its embedded snapshot.
build_mac_x64() {
  /usr/bin/arch -x86_64 /usr/bin/true 2>/dev/null \
    || die "Rosetta 2 not installed -- run: softwareupdate --install-rosetta --agree-to-license  (or set OAM_SKIP_MAC_X64=1 to drop the mac-x64 asset)"
  # --force-non-host: rustup refuses a foreign-host toolchain without it.
  rustup toolchain install stable-x86_64-apple-darwin --profile minimal --force-non-host
  # The C toolchain runs NATIVE (arm64), not under Rosetta. Command Line Tools
  # 27.0 ships libxcrun.dylib, clang and ld as arm64/arm64e only, so every
  # /usr/bin shim (cc, ar, xcrun, ...) that an x86_64 process launches -- and
  # rustc, cargo and every build script here ARE x86_64 -- inherits x86_64,
  # fails to dlopen libxcrun, and the link dies before any code is built
  # ("fat file, but missing compatible architecture (have 'arm64,arm64e',
  # need 'x86_64')"). An arm64 clang/ld handed `-arch x86_64` (rustc and the
  # cc crate both pass it) links a genuine x86_64 binary, so only the tools'
  # own architecture changes: cargo, rustc and the build scripts still run
  # x86_64 under Rosetta, which is what makes the V8 snapshot x64. The
  # wrappers go first on PATH (rustc's default linker is `cc`, the cc crate
  # finds `ar` and `xcrun` by name), and SDKROOT is resolved natively up front
  # because rustc and the cc crate would otherwise ask an x86_64 `xcrun`.
  local tools="target/x64-host/arm64-tools" tool
  mkdir -p "$tools"
  tools="$(cd "$tools" && pwd)"
  for tool in cc c++ clang clang++ ar ranlib ld libtool strip nm xcrun lipo; do
    [ -x "/usr/bin/$tool" ] || continue
    printf '#!/bin/sh\nexec /usr/bin/arch -arm64 /usr/bin/%s "$@"\n' "$tool" > "$tools/$tool"
    chmod +x "$tools/$tool"
  done
  local sdkroot
  sdkroot="$(/usr/bin/arch -arm64 /usr/bin/xcrun --sdk macosx --show-sdk-path)" \
    || die "could not resolve the macOS SDK path (xcrun --show-sdk-path)"
  PATH="$tools:$PATH" SDKROOT="$sdkroot" \
  CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER="$tools/cc" \
  CC_x86_64_apple_darwin="$tools/cc" CXX_x86_64_apple_darwin="$tools/c++" \
  AR_x86_64_apple_darwin="$tools/ar" \
  CARGO_TARGET_DIR=target/x64-host \
    cargo +stable-x86_64-apple-darwin build --release --target x86_64-apple-darwin -p oam_cli
  mkdir -p dist
  cp "target/x64-host/x86_64-apple-darwin/release/oam" "dist/oam-x86_64-apple-darwin"
  smoke "dist/oam-x86_64-apple-darwin"
  note "staged dist/oam-x86_64-apple-darwin (built under Rosetta 2)"
}

run_bench() {
  use_pinned_node
  # bun is optional (a missing bun just drops that column) -- try the official
  # installer once, non-blocking, matching bench.yml's install step.
  if ! command -v bun >/dev/null 2>&1; then
    export PATH="$HOME/.bun/bin:$PATH"
    if ! command -v bun >/dev/null 2>&1; then
      warn "bun not on PATH -- attempting install (non-blocking)"
      (curl -fsSL https://bun.sh/install | bash) >/dev/null 2>&1 \
        || warn "bun install failed -- bench runs without the bun column"
    fi
  fi
  node --version || true
  bun --version 2>/dev/null || true
  cargo run -p xtask -- bench --release --compare
}

run_io_uring_ab() {
  [ "$(uname -s)" = "Linux" ] || die "io-uring-ab is Linux-only"
  cargo build --release -p oam_cli
  echo "## baseline (io_uring off):"
  for _ in 1 2; do ./target/release/oam run bench/io_uring_ab.mjs --no-check; done
  echo "## io_uring on (OAM_IO_URING=1):"
  for _ in 1 2; do OAM_IO_URING=1 ./target/release/oam run bench/io_uring_ab.mjs --no-check; done
}

# Reclaim what cargo never collects, WITHOUT going cold.
#
# `rm -rf target/debug` after each build is the obvious move and the wrong one:
# the orchestrators deliberately preserve target/ across syncs so the dependency
# graph and the rusty_v8 static lib survive (a cold build on the GCP builder is
# ~30 min, an incremental one minutes). Deleting the tree buys disk by spending
# that 30 min on EVERY subsequent release.
#
# gc-target.sh is the surgical version and recovers the same disk: incremental/
# is pure cache and goes wholesale, while deps/ keeps each family`s current
# artifacts and drops only superseded copies, so the next run is still warm.
# Measured on the Linux builder 2026-08-22: 39GB -> 9GB, / from 10GB free to
# 40GB, build cache intact.
#
# --keep 3, not the default 1: a family can hold several LIVE artifacts, and
# evicting one forces a rebuild of it and everything that depends on it on the
# very next run. Measured from the debug maps of the Air's binaries (2026-09-25):
# up to 3 live rlibs per family -- getrandom 0.2/0.3/0.4, three serde_json and
# sha1 builds -- and a bin beside its test harnesses. --keep 2 evicted one of
# those on every run, so each run rebuilt it and the prune never converged.
# .rmeta families hold more live members still; gc-target.sh gives them 4x.
run_gc() {
  if [ ! -f scripts/gc-target.sh ]; then
    warn "scripts/gc-target.sh missing -- skipping target/ reclaim"
    return 0
  fi
  # Advisory by construction: a host that cannot prune must never fail a run
  # whose artifacts are already built.
  bash scripts/gc-target.sh --keep 3 || warn "target/ reclaim failed (non-blocking)"
}

# --- dispatch ----------------------------------------------------------------

case "$DISPATCH" in
  prep)         remote_prep ;;
  gate)         run_gate ;;
  test)         run_test ;;
  conformance)  run_conformance ;;
  surface-gaps) run_surface_gaps ;;
  node-suite)   run_node_suite ;;
  build)        build_host_release ;;
  bench)        run_bench ;;
  io-uring-ab)  run_io_uring_ab ;;
  gc)           run_gc ;;
  mac-release)
    remote_prep
    run_gate
    run_test
    # Conformance on the mac leg too, not just the Linux one. run_gate is
    # fmt+clippy only, so without this the differential corpus and the builtin
    # export-parity gate never execute on darwin -- and darwin-only native
    # code (fs statfs uses a DIFFERENT struct layout from linux) would ship
    # compile-checked but never run.
    run_conformance
    build_host_release
    if [ "${OAM_SKIP_MAC_X64:-0}" = "1" ]; then
      warn "OAM_SKIP_MAC_X64=1 -- mac-x64 asset dropped this run"
    else
      build_mac_x64
    fi
    ;;
  mac-measure)
    # node-compat.yml measure parity (continue-on-error): a tripped gate must
    # not discard the scorecard it just wrote -- the scorecard IS the product
    # here. xtask writes the scorecard before exiting non-zero on divergence /
    # ratchet violation, so the orchestrator's pull still gets fresh numbers.
    remote_prep
    run_conformance || warn "conformance diverged (advisory in measure mode)"
    run_node_suite  || warn "node-suite gate tripped (advisory in measure mode)"
    ;;
  mac-bench)
    remote_prep
    run_bench
    ;;
  *) die "unknown dispatch: $DISPATCH" ;;
esac

note "$DISPATCH complete"
