#!/bin/bash
# =============================================================================
# oam mac platform-build orchestrator  (Tailscale leg)
# =============================================================================
# Runs the mac legs of the deleted GitHub workflows on the Tailscale-reachable
# Apple-Silicon MacBook Air (the same host that builds yaw's mac leg). The
# Linux leg lives in scripts/build-platforms-gcp-iap.sh; this script exists
# because the Air is a personal machine, not a GCP VM -- Tailscale stays the
# right tool for it. Tailnet SSH is plain OpenSSH with keepalive, so the
# remote work runs as ONE ssh call per mode (no IAP-style sub-step splitting).
#
# Modes (remote dispatch in scripts/build-remote.sh):
#   --mode=release (default)   mac-release: prep + gate + test + native arm64
#                              build + x86_64-apple-darwin build via the x64
#                              HOST toolchain under Rosetta 2 (the snapshot
#                              must be generated by a target-arch process --
#                              see build-remote.sh header).
#       pulls:  $ART/oam-aarch64-apple-darwin
#               $ART/oam-x86_64-apple-darwin      (unless OAM_SKIP_MAC_X64=1)
#   --mode=measure             mac-measure: prep + conformance + node-suite
#       pulls:  $ART/mac-arm64/{scorecard.json,CONFORMANCE.md,
#                               node-suite-scorecard.json,CONFORMANCE-NODE.md}
#   --mode=bench               mac-bench: prep + bench
#       pulls:  $ART/mac-arm64/{BENCHMARKS.md,results.json}
#
# Usage (FAIL-CLOSED -- capture first, check the exit, THEN consume):
#   ART=$(./scripts/build-platforms-tailnet.sh) || { echo "mac leg failed"; exit 1; }
#   # Artifact dir = LAST stdout line; all progress goes to stderr.
#
# Host config (env; tailnet MagicDNS names or IPs -- `tailscale status`):
#   OAM_MAC_HOST      air.tailXXXX.ts.net   (required)
#   OAM_MAC_USER      account on the Mac    (required -- NOT $USER here)
#   OAM_MAC_KEY       SSH key path          (default: ~/.ssh/yaw_mac_air --
#                                            the key yaw's mac leg already
#                                            enrolled on the Air)
#   OAM_REMOTE_DIR    remote checkout path  (default: oam-build, under $HOME)
#   OAM_SKIP_MAC_X64=1  drop the x86_64-apple-darwin asset (release mode)
#
# Prereqs:
#   - Tailscale up on this box + the Air; ACLs allow SSH (22).
#   - Air toolchain: Xcode CLT + Node 22 (already there for yaw builds);
#     Rosetta 2 for the x64 leg (build-remote.sh names the install command
#     if missing). rustup auto-installs on first prep.
# =============================================================================

set -euo pipefail

MODE="release"
for arg in "$@"; do
  case "$arg" in
    --mode=release|--mode=measure|--mode=bench|--mode=surface-gaps) MODE="${arg#--mode=}" ;;
    -h|--help)
      awk 'NR==1{next} !/^#/{exit} {sub(/^# ?/, ""); print}' "$0"
      exit 0
      ;;
    *) echo "unknown arg: $arg (want --mode=release|measure|bench|surface-gaps)" >&2; exit 1 ;;
  esac
done

MAC_HOST="${OAM_MAC_HOST:?set OAM_MAC_HOST to the MacBook Air tailnet name or IP}"
MAC_USER="${OAM_MAC_USER:?set OAM_MAC_USER to the account on the MacBook Air (NOT \$USER from this box)}"
MAC_KEY="${OAM_MAC_KEY:-$HOME/.ssh/yaw_mac_air}"
REMOTE_DIR="${OAM_REMOTE_DIR:-oam-build}"
SKIP_MAC_X64="${OAM_SKIP_MAC_X64:-0}"

RED='\033[0;31m'; GRN='\033[0;32m'; YEL='\033[1;33m'; CYA='\033[1;36m'; NC='\033[0m'
ok()  { echo -e "${GRN}  [ok]${NC} $*" >&2; }
warn(){ echo -e "${YEL}  [warn]${NC} $*" >&2; }
fail(){ echo -e "${RED}  [fail]${NC} $*" >&2; exit 1; }
step(){ echo -e "\n${CYA}=== $* ===${NC}" >&2; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

RUNID="$(date +%Y%m%d-%H%M%S)"
STAGE_DIR="$(mktemp -d -t oam-tailnet-build-$RUNID-XXXXXX)"
ARTIFACTS_DIR="$STAGE_DIR/artifacts"
mkdir -p "$STAGE_DIR/logs" "$ARTIFACTS_DIR"

# Key-based NON-INTERACTIVE auth. BatchMode=yes makes a missing/rejected key
# fail fast (exit 255) instead of dropping to an interactive Password: prompt
# (which reads /dev/tty, bypassing log redirects, and hangs a background
# release forever). An ARRAY so a space in $MAC_KEY/$HOME survives; expand as
# "${SSH_OPTS[@]}" everywhere.
SSH_OPTS=(-i "$MAC_KEY" -o IdentitiesOnly=yes -o BatchMode=yes -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 -o ServerAliveInterval=30 -o ServerAliveCountMax=10)

# Working tree via tar + scp (rsync isn't on every macOS; tar/scp ship with
# OpenSSH). Remote target/ is PRESERVED across syncs -- xtask resolves the oam
# binary repo-relative, and the warm cargo cache is the difference between a
# ~30-min cold build and a minutes-long incremental one.
TAR_EXCLUDES=(--exclude=./.git --exclude=./target --exclude=./node_modules --exclude=./dist --exclude='*.log')

sync_src(){  # sync_src <user@host>
  ok "sync source -> $1:$REMOTE_DIR (remote target/ preserved)"
  # Explicit `|| return 1` per step: this runs inside build_mac, which is
  # invoked as `build_mac || handler` -- bash suppresses errexit in that whole
  # call tree, so without the returns a failed scp would still run the remote
  # extract against a stale/absent tarball.
  local t; t="$(mktemp "$STAGE_DIR/src-XXXXXX.tar.gz")" || return 1
  ( cd "$REPO_DIR" && tar czf "$t" "${TAR_EXCLUDES[@]}" . ) || return 1
  scp "${SSH_OPTS[@]}" -q "$t" "$1:oam-src.tar.gz" || return 1
  ssh "${SSH_OPTS[@]}" "$1" "mkdir -p $REMOTE_DIR && cd $REMOTE_DIR && find . -mindepth 1 -maxdepth 1 ! -name target -exec rm -rf {} + && tar xzf ~/oam-src.tar.gz && rm -f ~/oam-src.tar.gz" || return 1
  rm -f "$t"
}

pull(){  # pull <user@host> <remote-glob-under-REMOTE_DIR> <local-dir>
  scp "${SSH_OPTS[@]}" -q "$1:$REMOTE_DIR/$2" "$3"
}

# --- preflight ----------------------------------------------------------------
step "Run $RUNID -- oam mac --mode=$MODE on $MAC_USER@$MAC_HOST"
[ -f "$MAC_KEY" ] || fail "Mac SSH key not found: $MAC_KEY\n  One-time setup:\n    ssh-keygen -t ed25519 -N '' -C oam-mac-air -f \"$MAC_KEY\"\n    ssh-copy-id -i \"$MAC_KEY.pub\" $MAC_USER@$MAC_HOST\n  Already have a key on the Air? point at it with OAM_MAC_KEY=/path/to/key"
( cd "$REPO_DIR" && git diff --quiet HEAD ) || warn "working tree dirty -- uncommitted changes WILL ship"
ok "target: mac=$MAC_USER@$MAC_HOST (key: $MAC_KEY)"

# Resolve-time guard: catch a non-resolving OAM_MAC_HOST before scp hangs.
# getent on Linux/mac (NSS -> MagicDNS works); nslookup on Windows, grepped
# for a positive answer because it exits 0 even on NXDOMAIN.
resolve_check() {
  local host="$1"
  local err_msg="mac host '$host' does not resolve via DNS. Use the Tailscale MagicDNS name (run 'tailscale status') or the tailnet IP."
  if command -v getent >/dev/null 2>&1; then
    getent hosts "$host" >/dev/null 2>&1 || fail "$err_msg"
  elif command -v nslookup >/dev/null 2>&1; then
    local out
    out=$(nslookup -timeout=2 "$host" 2>&1) || true
    grep -qE "^Name:[[:space:]]+" <<<"$out" || fail "$err_msg"
  else
    warn "no resolver tool found (getent/nslookup) -- skipping resolve check for '$host'"
  fi
}
resolve_check "$MAC_HOST"

# Auth preflight: the key file existing proves nothing -- it must be enrolled
# in the Air's authorized_keys. One BatchMode probe surfaces cause + fix
# before any work.
probe_out=$(ssh "${SSH_OPTS[@]}" "$MAC_USER@$MAC_HOST" true 2>&1) || {
  case "$probe_out" in
    *"Permission denied"*)
      fail "Mac SSH key not enrolled on $MAC_HOST (key exists at $MAC_KEY, Air rejects it).\n  Enroll:  ssh-copy-id -i \"$MAC_KEY.pub\" $MAC_USER@$MAC_HOST" ;;
    *)
      fail "cannot reach $MAC_USER@$MAC_HOST over SSH:\n    $probe_out\n  Is the Air awake and on the tailnet? Check 'tailscale status'." ;;
  esac
}
ok "key auth OK on $MAC_USER@$MAC_HOST"

# --- build --------------------------------------------------------------------
# Called as `build_mac || handler` -- every step fails the function EXPLICITLY
# (bash suppresses set -e inside the || call tree).
build_mac(){
  local hp="$MAC_USER@$MAC_HOST"
  sync_src "$hp" || return 1
  case "$MODE" in
    release)
      ssh "${SSH_OPTS[@]}" "$hp" "cd $REMOTE_DIR && OAM_SKIP_MAC_X64=$SKIP_MAC_X64 bash scripts/build-remote.sh mac-release" || return 1
      pull "$hp" "dist/oam-aarch64-apple-darwin" "$ARTIFACTS_DIR/" || return 1
      if [ "$SKIP_MAC_X64" != "1" ]; then
        pull "$hp" "dist/oam-x86_64-apple-darwin" "$ARTIFACTS_DIR/" || return 1
      fi
      ;;
    measure)
      ssh "${SSH_OPTS[@]}" "$hp" "cd $REMOTE_DIR && bash scripts/build-remote.sh mac-measure" || return 1
      mkdir -p "$ARTIFACTS_DIR/mac-arm64" || return 1
      pull "$hp" "conformance/scorecard.json"            "$ARTIFACTS_DIR/mac-arm64/" || return 1
      pull "$hp" "conformance/node-suite-scorecard.json" "$ARTIFACTS_DIR/mac-arm64/" || return 1
      pull "$hp" "CONFORMANCE.md"                        "$ARTIFACTS_DIR/mac-arm64/" || return 1
      pull "$hp" "CONFORMANCE-NODE.md"                   "$ARTIFACTS_DIR/mac-arm64/" || return 1
      ;;
    bench)
      ssh "${SSH_OPTS[@]}" "$hp" "cd $REMOTE_DIR && bash scripts/build-remote.sh mac-bench" || return 1
      mkdir -p "$ARTIFACTS_DIR/mac-arm64" || return 1
      pull "$hp" "BENCHMARKS.md"      "$ARTIFACTS_DIR/mac-arm64/" || return 1
      pull "$hp" "bench/results.json" "$ARTIFACTS_DIR/mac-arm64/" || return 1
      ;;
    surface-gaps)
      ssh "${SSH_OPTS[@]}" "$hp" "cd $REMOTE_DIR && bash scripts/build-remote.sh surface-gaps" || return 1
      # The WHOLE ratchet file comes back, not a darwin fragment. The generator
      # merges: it rewrites only platforms[darwin] and leaves the win32/linux
      # sections exactly as they arrived in the sync. So the pulled file is
      # "what we sent, with darwin re-measured", which is safe to overwrite the
      # local copy with -- and is why these legs have to run one at a time,
      # each starting from the previous one's output.
      pull "$hp" "conformance/surface-gaps.json" "$REPO_DIR/conformance/" || return 1
      ;;
  esac
}

step "Run mac --mode=$MODE on $MAC_USER@$MAC_HOST"
build_mac > "$STAGE_DIR/logs/mac.log" 2>&1 \
  || { tail -30 "$STAGE_DIR/logs/mac.log" >&2; fail "mac leg failed -- see $STAGE_DIR/logs/mac.log"; }
ok "mac leg ok"

# --- verify -------------------------------------------------------------------
step "Verify staged artifacts"
find "$ARTIFACTS_DIR" -type f -exec ls -lh {} \; >&2
case "$MODE" in
  release)
    [ -f "$ARTIFACTS_DIR/oam-aarch64-apple-darwin" ] || fail "no mac-arm64 binary staged"
    if [ "$SKIP_MAC_X64" != "1" ]; then
      [ -f "$ARTIFACTS_DIR/oam-x86_64-apple-darwin" ] || fail "no mac-x64 binary staged"
    fi
    ;;
  measure) [ -f "$ARTIFACTS_DIR/mac-arm64/node-suite-scorecard.json" ] || fail "no scorecard staged" ;;
  bench)   [ -f "$ARTIFACTS_DIR/mac-arm64/results.json" ] || fail "no bench results staged" ;;
  surface-gaps)
    # Lands in the repo, not the staging dir -- assert darwin actually moved,
    # since a silently-unchanged section is the failure this mode exists to
    # prevent (the gate would then be measuring a host that never ran).
    node -e '
      const g = require(process.argv[1]);
      const d = g.platforms && g.platforms.darwin;
      if (!d) { console.error("no darwin section in the pulled ratchet"); process.exit(1); }
      console.error(`darwin: ${d.counts.present}/${d.counts.nodeExportNames} present, generated against ${d.generatedAgainst}`);
    ' "$REPO_DIR/conformance/surface-gaps.json" || fail "pulled ratchet has no darwin section"
    ;;
esac
ok "all required artifacts staged under $ARTIFACTS_DIR"

# LAST stdout line = the artifact dir, for ART=$(...) capture.
echo "$ARTIFACTS_DIR"
