#!/bin/bash
# =============================================================================
# oam release orchestrator -- replaces .github/workflows/release.yml (removed
# b2f8e24), following the yaw/vew GitHub-Actions-free pattern: local
# orchestrator scripts drive remote build hosts, then `gh release create`
# publishes from this box.
# =============================================================================
# Cuts a GitHub Release for a v* tag (created or re-pointed at HEAD by the
# preflight below -- see Usage) with these assets
# (exactly the names install/install.sh, install/install.ps1, and
# `oam self-update` consume):
#
#   oam-aarch64-pc-windows-msvc.exe   local, native (this dev box)
#   oam-x86_64-pc-windows-msvc.exe    local, x64 HOST toolchain under
#                                     Windows-on-ARM emulation (see below)
#   oam-aarch64-apple-darwin          MacBook Air (tailnet), native
#   oam-x86_64-apple-darwin           MacBook Air, x64 HOST toolchain under
#                                     Rosetta 2
#   oam-x86_64-unknown-linux-gnu      GCP Linux VM (IAP), native
#   SHA256SUMS
#   LICENSE, NOTICE, THIRD_PARTY_LICENSES.md   (attribution travels with the
#                                               binaries -- see the staging step)
#
# Why "HOST toolchain under emulation" for the x64 legs: oam cannot
# cross-compile (crates/oam_engine/build.rs -- the V8 startup snapshot must be
# generated by a process of the target architecture). Running the x86_64 HOST
# rustc under the OS's x64 emulation makes host arch == target arch, so the
# snapshot is generated by genuinely-x64 code. Slower than native; correct by
# construction. Each x64 binary is smoke-run under the same emulation before
# it ships.
#
# Compared to the deleted release.yml matrix: the four core targets are all
# still shipped, PLUS aarch64-pc-windows-msvc (which the hosted runners never
# covered on a private repo -- scripts/release-upload-local-arm64.sh used to
# patch it in after the fact; this script makes it a first-class asset).
# aarch64-unknown-linux-gnu remains unshipped (it was public-repo-gated and
# never released; needs an ARM Linux host, e.g. a GCP t2a VM, if wanted).
#
# Gates before anything uploads (ci.yml lived on push; with GHA gone the
# release IS the gate):
#   - scripts/ci-local.sh full (fmt/clippy/build/test/smoke/conformance/
#     node-suite) on this box            [OAM_SKIP_LOCAL_GATE=1 to skip]
#   - gate+test+conformance+node-suite on the Linux VM (inside --mode=release
#     -- the node-suite ratchet was node-compat.yml's ubuntu GATING job)
#   - gate+test on the Mac (inside mac-release)
#
# Usage -- the tag is managed for you. Bump Cargo.toml, commit, push, then:
#   ./scripts/release-local.sh v0.8.0
#
# Preflight creates <tag> at HEAD, or RE-POINTS it to HEAD if it already exists
# somewhere else (a stale tag from an abandoned attempt is the common case), and
# pushes it. That is safe only while the tag is unpublished, so the
# release-already-exists check runs FIRST and hard-fails: a tag whose release is
# live must keep pointing at the commit its assets were built from, forever.
# HEAD must already be on origin/main, since pushing the tag would otherwise
# publish an unpushed local commit.
#
# Env knobs:
#   OAM_SKIP_LOCAL_GATE=1   skip the local ci-local.sh run
#   OAM_SKIP_WIN_X64=1      drop the win-x64 asset (emulated build is slow)
#   OAM_SKIP_MAC=1          drop both mac assets (Air unreachable)
#   OAM_SKIP_MAC_X64=1      drop only the mac-x64 asset
#   OAM_SKIP_LINUX=1        drop the linux asset
#   OAM_KEEP_VM=1           leave the GCP VM running after the linux leg
#   OAM_DRY_RUN=1           build + checksum everything, publish nothing
#                           (release.yml's workflow_dispatch dry-run)
#
# The two remote legs run sequentially (simpler failure attribution). If
# release wall-time becomes a problem, they are independent and could run as
# background jobs with per-leg logs -- a future knob, not a v1 need.
#
# Signing seam: binaries ship UNSIGNED + checksummed (the @yawlabs
# distribution model -- scoop/curl/brew fetch bypass Gatekeeper/SmartScreen
# quarantine). To add Apple notarization / Windows Authenticode later, insert
# a signing step where each binary lands in $RELEASE_DIR, before the
# SHA256SUMS step. The rest of the pipeline is unchanged.
# =============================================================================

set -euo pipefail

TAG="${1:?usage: release-local.sh <tag>   (e.g. v0.8.0; created/re-pointed at HEAD for you)}"
REPO="YawLabs/oam"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_DIR"

RED='\033[0;31m'; GRN='\033[0;32m'; YEL='\033[1;33m'; CYA='\033[1;36m'; NC='\033[0m'
ok()  { echo -e "${GRN}  [ok]${NC} $*" >&2; }
warn(){ echo -e "${YEL}  [warn]${NC} $*" >&2; }
fail(){ echo -e "${RED}  [fail]${NC} $*" >&2; exit 1; }
step(){ echo -e "\n${CYA}=== $* ===${NC}" >&2; }

SKIP_LOCAL_GATE="${OAM_SKIP_LOCAL_GATE:-0}"
SKIP_WIN_X64="${OAM_SKIP_WIN_X64:-0}"
SKIP_MAC="${OAM_SKIP_MAC:-0}"
SKIP_LINUX="${OAM_SKIP_LINUX:-0}"

RELEASE_DIR="$(mktemp -d -t oam-release-"$TAG"-XXXXXX)"

# smoke <oam-binary>: ci.yml's smoke assertion, run on every staged binary
# this box can execute (win-arm64 native; win-x64 under the OS emulation).
smoke() {
  local bin="$1" d out
  d="$(mktemp -d)"
  echo "console.log('ci smoke', 6 * 7)" > "$d/smoke.js"
  # Guarded capture: under set -e a crash inside $() would kill the script
  # with no diagnostic and leak $d. 5-min ceiling = ci.yml's
  # timeout-minutes: 5 on the smoke step.
  if ! out="$(timeout 300 "$bin" run "$d/smoke.js")"; then
    rm -rf "$d"
    fail "smoke run failed (crash or 5-min hang) for $bin"
  fi
  rm -rf "$d"
  [ "$out" = "ci smoke 42" ] || fail "smoke output unexpected from $bin: '$out'"
  ok "smoke ok ($bin)"
}

# The gate's conformance + node-suite steps REGENERATE these committed
# artifacts with fresh commit/version stamps -- a prior (or this) run's gate
# self-dirties the tree with them. When they are the ONLY dirty paths,
# restore them to HEAD instead of failing: the content is machine-
# regenerated, reproducible by re-running xtask at this commit, and
# restoring keeps the tree the remote legs tar byte-identical to the tag.
CONFORMANCE_ARTIFACTS=(CONFORMANCE.md CONFORMANCE-NODE.md conformance/scorecard.json conformance/node-suite-scorecard.json)
restore_gate_artifacts() {  # restore_gate_artifacts <context>
  local dirty line path only_artifacts=1
  dirty="$(git status --porcelain)"
  [ -n "$dirty" ] || return 0
  while IFS= read -r line; do
    path="${line:3}"
    case "$path" in
      CONFORMANCE.md | CONFORMANCE-NODE.md | conformance/scorecard.json | conformance/node-suite-scorecard.json) ;;
      *) only_artifacts=0 ;;
    esac
  done <<<"$dirty"
  if [ "$only_artifacts" = "1" ]; then
    warn "$1: discarding gate-regenerated conformance artifacts (reproducible via xtask at this commit)"
    # HEAD explicitly (a bare `checkout --` restores from the INDEX and
    # would leave a staged artifact change dirty behind the warn).
    git checkout HEAD -- "${CONFORMANCE_ARTIFACTS[@]}"
  fi
  return 0
}

# --- preflight ----------------------------------------------------------------
step "Preflight $TAG"
command -v gh >/dev/null 2>&1 || fail "gh CLI not found"
gh auth status >/dev/null 2>&1 || fail "gh not authenticated -- run 'gh auth status' to inspect"

# --porcelain, not `git diff --quiet`: untracked files count too -- the
# remote legs tar the WORKING TREE, so an untracked file ships into builds.
# Leftover gate-regenerated conformance stamps (e.g. from a failed prior
# attempt) are auto-restored first; anything else dirty still fails.
# Checked BEFORE any tag work: never tag a tree we would refuse to build.
restore_gate_artifacts "preflight"
[ -z "$(git status --porcelain)" ] \
  || fail "working tree is dirty (untracked files count -- the remote legs ship the working tree) -- release from a clean tree"

# The binaries report the workspace version -- a v0.7.0 tag over a 0.6.1
# Cargo.toml would ship assets that self-identify wrong.
crate_version="$(awk -F'"' '/^version = /{print $2; exit}' Cargo.toml)"
[ "v$crate_version" = "$TAG" ] \
  || fail "tag $TAG != workspace version $crate_version (Cargo.toml) -- bump the version first"

head_sha="$(git rev-parse HEAD)"

# HEAD must already be on origin/main. This script creates the tag below, and
# `git push origin <tag>` drags the tagged commit along with it -- so without
# this an unpushed local commit could be published as a release.
git fetch -q origin main 2>/dev/null || true
git merge-base --is-ancestor "$head_sha" origin/main 2>/dev/null \
  || fail "HEAD ($head_sha) is not on origin/main -- push your commits first"

# A PUBLISHED tag is immutable: whatever the release assets were built from must
# keep pointing there forever. So check for the release FIRST, before the tag
# reconciliation below can move anything.
gh release view "$TAG" --repo "$REPO" >/dev/null 2>&1 \
  && fail "release $TAG already exists on $REPO (possibly a draft left by an interrupted run) -- inspect/delete it: gh release view $TAG --repo $REPO"

# Reconcile the tag to HEAD, creating or re-pointing as needed. Safe only
# because the release-exists check above already proved this tag is unpublished;
# moving a published tag would orphan the assets built from it.
# `git rev-parse <tag>` and the API's object.sha agree for both lightweight
# (commit SHA) and annotated (tag-object SHA) tags, so compare like with like.
local_tag_obj="$(git rev-parse "$TAG" 2>/dev/null || true)"
local_tag_commit="$(git rev-parse "${TAG}^{commit}" 2>/dev/null || true)"
remote_tag_obj="$(gh api "repos/$REPO/git/ref/tags/$TAG" --jq .object.sha 2>/dev/null || true)"

if [ "$local_tag_commit" = "$head_sha" ] \
   && [ -n "$remote_tag_obj" ] && [ "$remote_tag_obj" = "$local_tag_obj" ]; then
  ok "tag $TAG already at HEAD and in sync with origin"
else
  if [ -z "$local_tag_commit" ] && [ -z "$remote_tag_obj" ]; then
    ok "creating tag $TAG at HEAD ($head_sha)"
  else
    warn "re-pointing $TAG: ${local_tag_commit:-<absent>} -> $head_sha (unpublished, so safe to move)"
  fi
  if [ -n "$local_tag_obj" ]; then
    git tag -d "$TAG" >/dev/null || fail "could not delete local tag $TAG"
  fi
  if [ -n "$remote_tag_obj" ]; then
    git push -q origin ":refs/tags/$TAG" || fail "could not delete remote tag $TAG"
  fi
  git tag -a "$TAG" -m "$TAG" || fail "could not create tag $TAG"
  git push -q origin "$TAG" || fail "could not push tag $TAG"
  ok "tag $TAG now at $head_sha (local + origin)"
fi

# Re-read both sides from disk/remote rather than trusting what we just wrote.
tag_sha="$(git rev-parse "${TAG}^{commit}" 2>/dev/null)" || fail "tag $TAG missing after reconciliation"
[ "$tag_sha" = "$head_sha" ] || fail "tag $TAG ($tag_sha) still is not HEAD ($head_sha)"
remote_tag_obj="$(gh api "repos/$REPO/git/ref/tags/$TAG" --jq .object.sha 2>/dev/null)" \
  || fail "tag $TAG is not on the remote after push"
[ "$remote_tag_obj" = "$(git rev-parse "$TAG")" ] \
  || fail "remote tag $TAG ($remote_tag_obj) != local tag -- origin disagrees after push"

[ "$SKIP_MAC" = "1" ]   || [ -n "${OAM_MAC_HOST:-}" ] || fail "OAM_MAC_HOST not set (or set OAM_SKIP_MAC=1 to drop the mac assets)"
[ "$SKIP_LINUX" = "1" ] || command -v gcloud >/dev/null 2>&1 || fail "gcloud CLI not found (or set OAM_SKIP_LINUX=1 to drop the linux asset)"
ok "preflight ok (tag on remote, HEAD == $TAG, tree clean)"

# --- local gate ----------------------------------------------------------------
if [ "$SKIP_LOCAL_GATE" = "1" ]; then
  warn "OAM_SKIP_LOCAL_GATE=1 -- skipping the local CI gate"
else
  step "Local CI gate (scripts/ci-local.sh)"
  bash "$SCRIPT_DIR/ci-local.sh" || fail "local CI gate failed -- fix before releasing"
  # The gate just refreshed the conformance stamps; restore them so the
  # remote legs build from a tree byte-identical to the tag and the release
  # ends with a clean tree (no post-release stamp-refresh commit needed).
  restore_gate_artifacts "post-gate"
fi

# --- local Windows legs ---------------------------------------------------------
step "Build oam-aarch64-pc-windows-msvc.exe (local, native)"
# The resident type-check daemon holds oam.exe open; kill before rebuild.
# (Same precedent as scripts/release-upload-local-arm64.sh.)
taskkill //F //IM oam.exe 2>/dev/null || true
cargo build --release -p oam_cli
cp target/release/oam.exe "$RELEASE_DIR/oam-aarch64-pc-windows-msvc.exe"
smoke "$RELEASE_DIR/oam-aarch64-pc-windows-msvc.exe"

if [ "$SKIP_WIN_X64" = "1" ]; then
  warn "OAM_SKIP_WIN_X64=1 -- win-x64 asset dropped this release"
else
  step "Build oam-x86_64-pc-windows-msvc.exe (local, x64 toolchain under emulation)"
  # --force-non-host: rustup refuses a foreign-host toolchain without it.
  # CARGO_TARGET_DIR isolation keeps the x64 toolchain's host artifacts from
  # churning the native toolchain's fingerprints in target/.
  rustup toolchain install stable-x86_64-pc-windows-msvc --profile minimal --force-non-host
  CARGO_TARGET_DIR=target/x64-host \
    cargo +stable-x86_64-pc-windows-msvc build --release --target x86_64-pc-windows-msvc -p oam_cli
  cp target/x64-host/x86_64-pc-windows-msvc/release/oam.exe "$RELEASE_DIR/oam-x86_64-pc-windows-msvc.exe"
  smoke "$RELEASE_DIR/oam-x86_64-pc-windows-msvc.exe"   # runs under the OS's x64 emulation
fi

# --- remote legs (FAIL-CLOSED: capture, check exit, then consume) ---------------
if [ "$SKIP_MAC" = "1" ]; then
  warn "OAM_SKIP_MAC=1 -- mac assets dropped this release"
else
  step "Mac legs (tailnet: $OAM_MAC_HOST)"
  MAC_ART=$(bash "$SCRIPT_DIR/build-platforms-tailnet.sh" --mode=release) \
    || fail "mac leg failed -- see its log output above"
  MAC_ART="${MAC_ART##*$'\n'}"   # contract: artifact dir = LAST stdout line
  cp "$MAC_ART"/oam-*apple-darwin* "$RELEASE_DIR/"
fi

if [ "$SKIP_LINUX" = "1" ]; then
  warn "OAM_SKIP_LINUX=1 -- linux asset dropped this release"
else
  step "Linux leg (GCP IAP)"
  LINUX_ART=$(bash "$SCRIPT_DIR/build-platforms-gcp-iap.sh" --mode=release) \
    || fail "linux leg failed -- see its log output above"
  LINUX_ART="${LINUX_ART##*$'\n'}"   # contract: artifact dir = LAST stdout line
  cp "$LINUX_ART/oam-x86_64-unknown-linux-gnu" "$RELEASE_DIR/"
fi

# --- assemble + publish ----------------------------------------------------------
step "Assemble release assets + SHA256SUMS"
# Checksums cover the BINARIES only -- the license files are staged after this
# so they do not appear in a manifest install.sh verifies per-asset.
( cd "$RELEASE_DIR" && ls -lh oam-* >&2 && sha256sum oam-* > SHA256SUMS && cat SHA256SUMS >&2 )

# A released binary is a BINARY REDISTRIBUTION of V8 (BSD-3), ICU (Unicode),
# the Node streams port (MIT) and ~380 Rust crates -- every one of which
# requires its notice travel with the distribution. Apache-2.0 section 4(a)
# says the same about oam's own license. Shipping bare binaries met none of
# that, while NOTICE itself asserted the obligation applies to "every released
# oam binary". These three files are small next to a 57MB binary and are the
# difference between the claim and the fact.
step "Stage license + attribution alongside the binaries"
for f in LICENSE NOTICE THIRD_PARTY_LICENSES.md; do
  [ -f "$REPO_DIR/$f" ] || fail "$f missing from the repo -- it must ship with the release"
  cp "$REPO_DIR/$f" "$RELEASE_DIR/$f"
done
ok "LICENSE, NOTICE and THIRD_PARTY_LICENSES.md staged"

if [ "${OAM_DRY_RUN:-0}" = "1" ]; then
  # release.yml's workflow_dispatch dry-run: build + checksum, publish nothing.
  step "DRY RUN -- skipping gh release create"
  ok "assets staged + checksummed at $RELEASE_DIR (nothing published)"
  exit 0
fi

step "Cut GitHub Release $TAG"
# Draft-first publish: assets upload while the release is still a draft, and
# it goes live -- atomically, one API call -- only once every asset is up. A
# mid-upload failure leaves a DRAFT (delete it and re-run), never a live
# half-release that install.sh / self-update could resolve.
gh release create "$TAG" "$RELEASE_DIR"/* \
  --repo "$REPO" \
  --title "$TAG" \
  --generate-notes \
  --verify-tag \
  --draft
gh release edit "$TAG" --repo "$REPO" --draft=false
ok "release $TAG published: https://github.com/$REPO/releases/tag/$TAG"
ok "staged assets kept at $RELEASE_DIR (safe to delete)"

# --- publish the installers to oamjs.org -----------------------------------------
# `oam self-update` fetches https://oamjs.org/install.{sh,ps1} and pipes the
# result into sh / iex. Those files are COPIES of install/ served by a separate
# repo, so without this step the site can silently drift from the release that
# ships with it -- and the failure lands in a user's shell, not in CI.
#
# Skipped rather than fatal when the site checkout is absent: a release is still
# valid without it, and the verification below says loudly if the live site is
# stale.
# --- sidecar regression matrix --------------------------------------------------
# Yaw MCP ships `defaultRuntime: "oam"`, so a release that breaks a sidecar
# breaks the broker for real users. Gating here is the difference between
# catching it and shipping it. Network- and npm-dependent, so a failure to RUN
# the matrix warns; a sidecar that actually fails is fatal.
step "MCP sidecar regression matrix"
if ! command -v node >/dev/null 2>&1; then
  warn "node not on PATH -- sidecar matrix skipped (it hosts the harness, not the test)"
else
  set +e
  # The freshly built NATIVE asset -- the matrix must exercise the binary this
  # release actually ships, not whatever oam happens to be on PATH.
  OAM_BIN="$RELEASE_DIR/oam-aarch64-pc-windows-msvc.exe" node "$REPO_DIR/scripts/mcp-sidecar-matrix.mjs"
  matrix_status=$?
  set -e
  case "$matrix_status" in
    0) ok "every oam-hosted sidecar served its tools" ;;
    1) fail "a sidecar failed on this build -- see above; do NOT ship" ;;
    *) warn "sidecar matrix could not complete (status $matrix_status) -- result is INCOMPLETE, not clean" ;;
  esac
fi

step "Publish installers to oamjs.org"
SITE_DIR="${OAM_SITE_DIR:-$REPO_DIR/../oamjs.org}"
if [ ! -d "$SITE_DIR/public" ]; then
  warn "no site checkout at $SITE_DIR -- installers NOT republished (clone YawLabs/oamjs.org, or set OAM_SITE_DIR)"
else
  cp "$REPO_DIR/install/install.sh" "$SITE_DIR/public/install.sh"
  cp "$REPO_DIR/install/install.ps1" "$SITE_DIR/public/install.ps1"
  if git -C "$SITE_DIR" diff --quiet -- public/install.sh public/install.ps1; then
    ok "oamjs.org installers already match this release"
  else
    git -C "$SITE_DIR" add public/install.sh public/install.ps1
    git -C "$SITE_DIR" commit -q -m "Sync installers from oam $TAG"
    git -C "$SITE_DIR" push -q
    ( cd "$SITE_DIR" && netlify deploy --prod --dir public >/dev/null 2>&1 )       && ok "oamjs.org installers republished"       || warn "netlify deploy failed -- run 'netlify deploy --prod --dir public' in $SITE_DIR"
  fi
fi

# Verify what the SITE actually serves, not what we just uploaded: a stale CDN
# copy is exactly the failure this step exists to prevent, and it is invisible
# from the filesystem.
step "Verify oamjs.org serves this release's installers"
for f in install.sh install.ps1; do
  live="$(curl -fsSL --max-time 30 "https://oamjs.org/$f" 2>/dev/null || true)"
  if [ -z "$live" ]; then
    warn "https://oamjs.org/$f did not fetch -- self-update is BROKEN until it does"
  elif [ "$live" = "$(cat "$REPO_DIR/install/$f")" ]; then
    ok "https://oamjs.org/$f matches install/$f"
  else
    warn "https://oamjs.org/$f DIFFERS from install/$f -- self-update will run the stale copy"
  fi
done
