#!/bin/bash
# =============================================================================
# oam release orchestrator -- replaces .github/workflows/release.yml (removed
# b2f8e24), following the yaw/vew GitHub-Actions-free pattern: local
# orchestrator scripts drive remote build hosts, then `gh release create`
# publishes from this box.
# =============================================================================
# Cuts a GitHub Release for a v* tag (created or re-pointed at HEAD by the
# preflight below -- see Usage) with these assets
# (exactly the names install/install.sh, install/install.ps1, and
# `oam self-update` consume):
#
#   oam-aarch64-pc-windows-msvc.exe   local, native (this dev box)
#   oam-x86_64-pc-windows-msvc.exe    local, x64 HOST toolchain under
#                                     Windows-on-ARM emulation (see below)
#   oam-aarch64-apple-darwin          MacBook Air (tailnet), native
#   oam-x86_64-apple-darwin           MacBook Air, x64 HOST toolchain under
#                                     Rosetta 2
#   oam-x86_64-unknown-linux-gnu      GCP Linux VM (IAP), native
#   SHA256SUMS
#   LICENSE, NOTICE, THIRD_PARTY_LICENSES.md   (attribution travels with the
#                                               binaries -- see the staging step)
#
# Why "HOST toolchain under emulation" for the x64 legs: oam cannot
# cross-compile (crates/oam_engine/build.rs -- the V8 startup snapshot must be
# generated by a process of the target architecture). Running the x86_64 HOST
# rustc under the OS's x64 emulation makes host arch == target arch, so the
# snapshot is generated by genuinely-x64 code. Slower than native; correct by
# construction. Each x64 binary is smoke-run under the same emulation before
# it ships.
#
# Compared to the deleted release.yml matrix: the four core targets are all
# still shipped, PLUS aarch64-pc-windows-msvc (which the hosted runners never
# covered on a private repo -- scripts/release-upload-local-arm64.sh used to
# patch it in after the fact; this script makes it a first-class asset).
# aarch64-unknown-linux-gnu remains unshipped (it was public-repo-gated and
# never released; needs an ARM Linux host, e.g. a GCP t2a VM, if wanted).
#
# Gates before anything uploads (ci.yml lived on push; with GHA gone the
# release IS the gate):
#   - scripts/ci-local.sh full (fmt/clippy/build/test/smoke/conformance/
#     node-suite) on this box            [OAM_SKIP_LOCAL_GATE=1 to skip]
#   - gate+test+conformance+node-suite on the Linux VM (inside --mode=release
#     -- the node-suite ratchet was node-compat.yml's ubuntu GATING job)
#   - gate+test on the Mac (inside mac-release)
#
# Usage -- the tag AND the version are managed for you:
#   ./scripts/release-local.sh v0.8.0
#
# The tag is the request. If the workspace version does not already match it,
# preflight bumps Cargo.toml to <tag> minus the leading v, refreshes Cargo.lock
# (`cargo update --workspace --offline` -- workspace members only, no
# third-party drift), commits and pushes to main -- exactly the manual step this
# note used to prescribe. Guarded: forward-only (never downgrades), plain
# vMAJOR.MINOR.PATCH tags only, requires HEAD == origin/main on main so the
# commit fast-forwards, and refuses if the bump touched anything but
# Cargo.toml + Cargo.lock. OAM_NO_AUTO_BUMP=1 restores the old hard-fail.
#
# Preflight creates <tag> at HEAD, or RE-POINTS it to HEAD if it already exists
# somewhere else (a stale tag from an abandoned attempt is the common case), and
# pushes it. That is safe only while the tag is unpublished, so the
# release-already-exists check runs FIRST and hard-fails: a tag whose release is
# live must keep pointing at the commit its assets were built from, forever.
# HEAD must already be on origin/main, since pushing the tag would otherwise
# publish an unpushed local commit.
#
# Env knobs:
#   OAM_NO_AUTO_BUMP=1      never write Cargo.toml; hard-fail on a version
#                           mismatch the way this script used to
#   OAM_SKIP_LOCAL_GATE=1   skip the local ci-local.sh run
#   OAM_SKIP_WIN_X64=1      drop the win-x64 asset (emulated build is slow)
#   OAM_SKIP_MAC=1          drop both mac assets (Air unreachable)
#   OAM_SKIP_MAC_X64=1      drop only the mac-x64 asset
#   OAM_SKIP_LINUX=1        drop the linux asset
#   OAM_KEEP_VM=1           leave the GCP VM running after the linux leg
#   OAM_DRY_RUN=1           build + checksum everything, publish nothing
#                           (release.yml's workflow_dispatch dry-run). Preflight
#                           still runs in full -- it bumps, commits and tags, so
#                           the dry-run builds the binaries the real release
#                           would; only the upload is skipped.
#
# The two remote legs run sequentially (simpler failure attribution). If
# release wall-time becomes a problem, they are independent and could run as
# background jobs with per-leg logs -- a future knob, not a v1 need.
#
# Signing seam: binaries ship UNSIGNED + checksummed (the @yawlabs
# distribution model -- scoop/curl/brew fetch bypass Gatekeeper/SmartScreen
# quarantine). To add Apple notarization / Windows Authenticode later, insert
# a signing step where each binary lands in $RELEASE_DIR, before the
# SHA256SUMS step. The rest of the pipeline is unchanged.
# =============================================================================

set -euo pipefail

TAG="${1:?usage: release-local.sh <tag>   (e.g. v0.8.0; created/re-pointed at HEAD for you)}"
REPO="YawLabs/oam"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_DIR"

RED='\033[0;31m'; GRN='\033[0;32m'; YEL='\033[1;33m'; CYA='\033[1;36m'; NC='\033[0m'
ok()  { echo -e "${GRN}  [ok]${NC} $*" >&2; }
warn(){ echo -e "${YEL}  [warn]${NC} $*" >&2; }
fail(){ echo -e "${RED}  [fail]${NC} $*" >&2; exit 1; }
step(){ echo -e "\n${CYA}=== $* ===${NC}" >&2; }

SKIP_LOCAL_GATE="${OAM_SKIP_LOCAL_GATE:-0}"
SKIP_WIN_X64="${OAM_SKIP_WIN_X64:-0}"
SKIP_MAC="${OAM_SKIP_MAC:-0}"
SKIP_LINUX="${OAM_SKIP_LINUX:-0}"

RELEASE_DIR="$(mktemp -d -t oam-release-"$TAG"-XXXXXX)"

# smoke <oam-binary>: ci.yml's smoke assertion, run on every staged binary
# this box can execute (win-arm64 native; win-x64 under the OS emulation).
smoke() {
  local bin="$1" d out
  d="$(mktemp -d)"
  echo "console.log('ci smoke', 6 * 7)" > "$d/smoke.js"
  # Guarded capture: under set -e a crash inside $() would kill the script
  # with no diagnostic and leak $d. 5-min ceiling = ci.yml's
  # timeout-minutes: 5 on the smoke step.
  if ! out="$(timeout 300 "$bin" run "$d/smoke.js")"; then
    rm -rf "$d"
    fail "smoke run failed (crash or 5-min hang) for $bin"
  fi
  rm -rf "$d"
  [ "$out" = "ci smoke 42" ] || fail "smoke output unexpected from $bin: '$out'"
  ok "smoke ok ($bin)"
}

# The gate's conformance + node-suite steps REGENERATE these committed
# artifacts with fresh commit/version stamps -- a prior (or this) run's gate
# self-dirties the tree with them. When they are the ONLY dirty paths,
# restore them to HEAD instead of failing: the content is machine-
# regenerated, reproducible by re-running xtask at this commit, and
# restoring keeps the tree the remote legs tar byte-identical to the tag.
CONFORMANCE_ARTIFACTS=(CONFORMANCE.md CONFORMANCE-NODE.md conformance/scorecard.json conformance/node-suite-scorecard.json)
restore_gate_artifacts() {  # restore_gate_artifacts <context>
  local dirty line path only_artifacts=1
  dirty="$(git status --porcelain)"
  [ -n "$dirty" ] || return 0
  while IFS= read -r line; do
    path="${line:3}"
    case "$path" in
      CONFORMANCE.md | CONFORMANCE-NODE.md | conformance/scorecard.json | conformance/node-suite-scorecard.json) ;;
      *) only_artifacts=0 ;;
    esac
  done <<<"$dirty"
  if [ "$only_artifacts" = "1" ]; then
    warn "$1: discarding gate-regenerated conformance artifacts (reproducible via xtask at this commit)"
    # HEAD explicitly (a bare `checkout --` restores from the INDEX and
    # would leave a staged artifact change dirty behind the warn).
    git checkout HEAD -- "${CONFORMANCE_ARTIFACTS[@]}"
  fi
  return 0
}

# free_locked_binary <path>
# Windows refuses to DELETE or overwrite a RUNNING .exe, so cargo's link step
# dies with "failed to remove file <path>: Access is denied (os error 5)". It
# does allow RENAMING one: the running processes keep their handle to the
# renamed file and carry on, and the name is free for the new build.
#
# This used to be `taskkill //F //IM oam.exe`, which is both hostile and racy.
# The release binary is what live typed-cli sessions run
# (`target/release/oam.exe run ~/.config/typed/typed-cli/cli.mjs -- --resume`),
# so the kill took out the operator's OTHER agent panes -- and they come back
# on --resume within seconds, re-locking the file before the link step reached
# it. Observed on the v0.8.2 attempt: three sessions all restarted at 16:40:22
# and the build failed anyway. A rename kills nothing and cannot lose that race.
free_locked_binary() {
  local path="$1" parked
  [ -f "$path" ] || return 0
  parked="$path.inuse-$(date +%s)"
  mv "$path" "$parked" 2>/dev/null || true
  # Best effort: Windows will not unlink it while a process still has the image
  # mapped, and that is fine -- a parked copy is some MB inside gitignored
  # target/, and the sweep below reaps it on a later run once the holder exits.
  rm -f "$parked" 2>/dev/null || true
  rm -f "$path".inuse-* 2>/dev/null || true
  if [ -f "$path" ]; then
    fail "could not free $path -- something holds it that a rename cannot dislodge (check: Get-Process oam | Select-Object Id,Path)"
  fi
  ok "parked the in-use $(basename "$path") (live sessions left running)"
  return 0
}

# push_bump_to_main <commit-subject> <expected-version>
# main carries a ruleset (verified signatures + PR-only). This account holds
# bypass, so a direct push lands and GitHub just prints "Bypassed rule
# violations" -- that notice is the NORMAL path here, not a failure, and
# nothing above or below reacts to it.
#
# The fallback exists for when the bypass is not in play (different account,
# tightened ruleset, org plan change): the push is REJECTED outright and the
# release would otherwise die holding an unpushed bump commit that the tag push
# below would then refuse to publish. So drive the flow the rules DO allow,
# end to end and unattended -- branch, PR, `gh pr merge --admin` (the
# documented override for a ruleset-gated merge) -- then realign local main to
# whatever origin ended up with, because a squash merge mints a new SHA.
push_bump_to_main() {
  local subject="$1" want_version="$2" branch_name merged_sha
  if git push origin main; then
    ok "bump pushed to main"
    return 0
  fi
  warn "direct push to main rejected (no rule bypass in play) -- routing through a PR with --admin"
  branch_name="release/bump-$(git rev-parse --short HEAD)"
  git push -q origin "HEAD:refs/heads/$branch_name" \
    || fail "could not push $branch_name -- the bump commit is local-only; land it by hand and re-run"
  gh pr create --repo "$REPO" --base main --head "$branch_name" \
    --title "$subject" --body "Automated version bump from scripts/release-local.sh." >/dev/null \
    || fail "could not open the bump PR for $branch_name"
  gh pr merge "$branch_name" --repo "$REPO" --squash --admin --delete-branch >/dev/null \
    || fail "could not merge the bump PR even with --admin -- this account may not hold bypass; merge $branch_name by hand and re-run"
  git fetch -q origin main || fail "could not fetch origin/main after the merge"
  merged_sha="$(git rev-parse origin/main)"
  # Discards exactly one thing: the local bump commit, now superseded by the
  # squashed equivalent on origin. The tree was clean before the bump, and the
  # version assertion below proves the content survived the round trip.
  git reset --hard "$merged_sha" >/dev/null || fail "could not realign local main to origin/main"
  [ "$(awk -F'"' '/^version = /{print $2; exit}' Cargo.toml)" = "$want_version" ] \
    || fail "origin/main does not carry the $want_version bump after the merge -- inspect $REPO"
  ok "bump merged via PR (--admin), local main realigned to $merged_sha"
}

# --- preflight ----------------------------------------------------------------
step "Preflight $TAG"
command -v gh >/dev/null 2>&1 || fail "gh CLI not found"
gh auth status >/dev/null 2>&1 || fail "gh not authenticated -- run 'gh auth status' to inspect"

# --porcelain, not `git diff --quiet`: untracked files count too -- the
# remote legs tar the WORKING TREE, so an untracked file ships into builds.
# Leftover gate-regenerated conformance stamps (e.g. from a failed prior
# attempt) are auto-restored first; anything else dirty still fails.
# Checked BEFORE any tag work: never tag a tree we would refuse to build.
restore_gate_artifacts "preflight"
[ -z "$(git status --porcelain)" ] \
  || fail "working tree is dirty (untracked files count -- the remote legs ship the working tree) -- release from a clean tree"

# origin/main is load-bearing for BOTH the auto-bump (which pushes a commit
# onto it) and the ancestor check further down, so refresh it before either.
git fetch -q origin main 2>/dev/null || true

# A PUBLISHED tag is immutable: whatever the release assets were built from must
# keep pointing there forever. So check for the release FIRST -- before the
# auto-bump commits anything or the tag reconciliation moves anything.
gh release view "$TAG" --repo "$REPO" >/dev/null 2>&1 \
  && fail "release $TAG already exists on $REPO (possibly a draft left by an interrupted run) -- inspect/delete it: gh release view $TAG --repo $REPO"

# The binaries report the workspace version -- a v0.7.0 tag over a 0.6.1
# Cargo.toml would ship assets that self-identify wrong. The tag IS the
# request, so reconcile the version TO it instead of making the caller
# remember a separate bump-commit-push step and re-run.
crate_version="$(awk -F'"' '/^version = /{print $2; exit}' Cargo.toml)"
[ -n "$crate_version" ] || fail "could not read the workspace version from Cargo.toml"
tag_version="${TAG#v}"

if [ "$tag_version" = "$crate_version" ]; then
  ok "workspace version already $crate_version"
elif [ "${OAM_NO_AUTO_BUMP:-0}" = "1" ]; then
  fail "tag $TAG != workspace version $crate_version (Cargo.toml) -- bump the version first (OAM_NO_AUTO_BUMP=1 disables the auto-bump)"
else
  # Guards. Each one is a way the bump could do something the caller did not
  # ask for, so each fails rather than improvises.
  #
  # 1. Only a plain vMAJOR.MINOR.PATCH tag maps onto a Cargo version by
  #    stripping the v. Prerelease/build metadata never shipped here; guessing
  #    what it should mean is worse than handing it back.
  printf '%s' "$tag_version" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$' \
    || fail "$TAG is not a plain vMAJOR.MINOR.PATCH tag -- set the version in Cargo.toml yourself, commit, push, and re-run"
  # 2. Forward only. sort -V puts the lower version first, so if that is not
  #    the current one, the tag is BEHIND the tree. Version sort, not string
  #    comparison, which would call 0.8.10 older than 0.8.2.
  [ "$(printf '%s\n%s\n' "$crate_version" "$tag_version" | sort -V | head -1)" = "$crate_version" ] \
    || fail "tag $TAG is BEHIND the workspace version $crate_version -- refusing to downgrade Cargo.toml"
  # 3. The bump becomes a commit on main that the tag will point at, so it has
  #    to fast-forward: on main, and exactly AT origin/main. The ancestor check
  #    below tolerates a HEAD that is merely behind origin/main; committing on
  #    top of one would diverge and the push would be rejected.
  branch="$(git rev-parse --abbrev-ref HEAD)"
  [ "$branch" = "main" ] \
    || fail "auto-bump commits to main, but HEAD is on '$branch' -- switch to main (or bump Cargo.toml yourself and re-run)"
  origin_main="$(git rev-parse --verify --quiet origin/main || true)"
  [ -n "$origin_main" ] || fail "no origin/main locally -- run 'git fetch origin main' first"
  [ "$(git rev-parse HEAD)" = "$origin_main" ] \
    || fail "main is not level with origin/main -- the bump commit would not fast-forward; pull/push first"

  warn "workspace version $crate_version != $TAG -- bumping Cargo.toml to $tag_version"
  # First `^version = "` line only -- that is [workspace.package], which every
  # member inherits via version.workspace = true. Rewritten through a temp file
  # OUTSIDE the repo, so a failed rewrite cannot leave an untracked file behind
  # to trip the clean-tree check on the next run.
  bump_tmp="$(mktemp)"
  awk -v new="$tag_version" 'BEGIN{d=0} /^version = "/ && !d {sub(/"[^"]*"/, "\"" new "\""); d=1} {print}' \
    Cargo.toml > "$bump_tmp" || { rm -f "$bump_tmp"; fail "could not rewrite Cargo.toml"; }
  cp "$bump_tmp" Cargo.toml
  rm -f "$bump_tmp"
  # Re-read from disk rather than trusting the rewrite.
  bumped_version="$(awk -F'"' '/^version = /{print $2; exit}' Cargo.toml)"
  [ "$bumped_version" = "$tag_version" ] \
    || fail "Cargo.toml still reads '$bumped_version' after the bump -- fix it by hand"

  # The lock pins every workspace member's version too. Leaving it stale means
  # the first cargo build rewrites it and dirties the tree the remote legs tar
  # -- and process.versions is published FROM Cargo.lock at build time.
  # --workspace --offline: local members only, no registry access, so a release
  # can never quietly drag third-party deps forward as a side effect.
  cargo update --workspace --offline >&2 \
    || fail "could not refresh Cargo.lock ('cargo update --workspace --offline') -- fix and re-run"

  # The tree was clean coming in, so the bump's footprint should be exactly
  # these two paths. Anything else means something ran that should not have.
  bump_paths="$(git status --porcelain | awk '{print $2}' | sort | tr '\n' ' ')"
  [ "$bump_paths" = "Cargo.lock Cargo.toml " ] \
    || fail "the bump touched unexpected paths ($bump_paths) -- inspect the tree and commit yourself"

  git add Cargo.toml Cargo.lock || fail "could not stage the version bump"
  git commit -q -m "chore(release): bump workspace version to $tag_version" \
    || fail "could not commit the version bump"
  # Pushed here, not left local: the tag push below drags the tagged commit
  # along with it, and a release must never point at a commit that only exists
  # on this box. Rule bypass (or --admin, if the bypass is not in play) is the
  # expected path -- see push_bump_to_main.
  push_bump_to_main "chore(release): bump workspace version to $tag_version" "$tag_version"
  ok "bumped $crate_version -> $tag_version and landed on main"
fi

# Re-read HEAD from git rather than reusing anything captured before the bump.
head_sha="$(git rev-parse HEAD)"

# HEAD must already be on origin/main. This script creates the tag below, and
# `git push origin <tag>` drags the tagged commit along with it -- so without
# this an unpushed local commit could be published as a release.
git merge-base --is-ancestor "$head_sha" origin/main 2>/dev/null \
  || fail "HEAD ($head_sha) is not on origin/main -- push your commits first"

# Reconcile the tag to HEAD, creating or re-pointing as needed. Safe only
# because the release-exists check above already proved this tag is unpublished;
# moving a published tag would orphan the assets built from it.
# `git rev-parse <tag>` and the API's object.sha agree for both lightweight
# (commit SHA) and annotated (tag-object SHA) tags, so compare like with like.
# --verify --quiet is load-bearing: plain `git rev-parse <unknown-ref>` ECHOES
# the argument on stdout as well as failing, so these came back as the literal
# strings "v0.8.1" and "v0.8.1^{commit}" for a tag that did not exist. Non-empty
# meant "tag exists", so a first-time tag took the re-point branch and then died
# trying to delete a tag that was never there -- breaking every NEW release tag.
local_tag_obj="$(git rev-parse --verify --quiet "$TAG" 2>/dev/null || true)"
local_tag_commit="$(git rev-parse --verify --quiet "${TAG}^{commit}" 2>/dev/null || true)"
remote_tag_obj="$(gh api "repos/$REPO/git/ref/tags/$TAG" --jq .object.sha 2>/dev/null || true)"

if [ "$local_tag_commit" = "$head_sha" ] \
   && [ -n "$remote_tag_obj" ] && [ "$remote_tag_obj" = "$local_tag_obj" ]; then
  ok "tag $TAG already at HEAD and in sync with origin"
else
  if [ -z "$local_tag_commit" ] && [ -z "$remote_tag_obj" ]; then
    ok "creating tag $TAG at HEAD ($head_sha)"
  else
    warn "re-pointing $TAG: ${local_tag_commit:-<absent>} -> $head_sha (unpublished, so safe to move)"
  fi
  if [ -n "$local_tag_obj" ]; then
    git tag -d "$TAG" >/dev/null || fail "could not delete local tag $TAG"
  fi
  if [ -n "$remote_tag_obj" ]; then
    git push -q origin ":refs/tags/$TAG" || fail "could not delete remote tag $TAG"
  fi
  git tag -a "$TAG" -m "$TAG" || fail "could not create tag $TAG"
  git push -q origin "$TAG" || fail "could not push tag $TAG"
  ok "tag $TAG now at $head_sha (local + origin)"
fi

# Re-read both sides from disk/remote rather than trusting what we just wrote.
tag_sha="$(git rev-parse "${TAG}^{commit}" 2>/dev/null)" || fail "tag $TAG missing after reconciliation"
[ "$tag_sha" = "$head_sha" ] || fail "tag $TAG ($tag_sha) still is not HEAD ($head_sha)"
remote_tag_obj="$(gh api "repos/$REPO/git/ref/tags/$TAG" --jq .object.sha 2>/dev/null)" \
  || fail "tag $TAG is not on the remote after push"
[ "$remote_tag_obj" = "$(git rev-parse "$TAG")" ] \
  || fail "remote tag $TAG ($remote_tag_obj) != local tag -- origin disagrees after push"

[ "$SKIP_MAC" = "1" ]   || [ -n "${OAM_MAC_HOST:-}" ] || fail "OAM_MAC_HOST not set (or set OAM_SKIP_MAC=1 to drop the mac assets)"
[ "$SKIP_LINUX" = "1" ] || command -v gcloud >/dev/null 2>&1 || fail "gcloud CLI not found (or set OAM_SKIP_LINUX=1 to drop the linux asset)"
ok "preflight ok (tag on remote, HEAD == $TAG, tree clean)"

# --- local gate ----------------------------------------------------------------
if [ "$SKIP_LOCAL_GATE" = "1" ]; then
  warn "OAM_SKIP_LOCAL_GATE=1 -- skipping the local CI gate"
else
  step "Local CI gate (scripts/ci-local.sh)"
  bash "$SCRIPT_DIR/ci-local.sh" || fail "local CI gate failed -- fix before releasing"
  # The gate just refreshed the conformance stamps; restore them so the
  # remote legs build from a tree byte-identical to the tag and the release
  # ends with a clean tree (no post-release stamp-refresh commit needed).
  restore_gate_artifacts "post-gate"
fi

# --- local Windows legs ---------------------------------------------------------
step "Build oam-aarch64-pc-windows-msvc.exe (local, native)"
# Live processes run this exact file -- typed-cli sessions, the resident
# type-check daemon. Park it rather than killing them (see free_locked_binary;
# scripts/release-upload-local-arm64.sh still has the old taskkill).
free_locked_binary target/release/oam.exe
cargo build --release -p oam_cli
cp target/release/oam.exe "$RELEASE_DIR/oam-aarch64-pc-windows-msvc.exe"
smoke "$RELEASE_DIR/oam-aarch64-pc-windows-msvc.exe"

if [ "$SKIP_WIN_X64" = "1" ]; then
  warn "OAM_SKIP_WIN_X64=1 -- win-x64 asset dropped this release"
else
  step "Build oam-x86_64-pc-windows-msvc.exe (local, x64 toolchain under emulation)"
  # --force-non-host: rustup refuses a foreign-host toolchain without it.
  # CARGO_TARGET_DIR isolation keeps the x64 toolchain's host artifacts from
  # churning the native toolchain's fingerprints in target/.
  rustup toolchain install stable-x86_64-pc-windows-msvc --profile minimal --force-non-host
  CARGO_TARGET_DIR=target/x64-host \
    cargo +stable-x86_64-pc-windows-msvc build --release --target x86_64-pc-windows-msvc -p oam_cli
  cp target/x64-host/x86_64-pc-windows-msvc/release/oam.exe "$RELEASE_DIR/oam-x86_64-pc-windows-msvc.exe"
  smoke "$RELEASE_DIR/oam-x86_64-pc-windows-msvc.exe"   # runs under the OS's x64 emulation
fi

# --- remote legs (FAIL-CLOSED: capture, check exit, then consume) ---------------
if [ "$SKIP_MAC" = "1" ]; then
  warn "OAM_SKIP_MAC=1 -- mac assets dropped this release"
else
  step "Mac legs (tailnet: $OAM_MAC_HOST)"
  MAC_ART=$(bash "$SCRIPT_DIR/build-platforms-tailnet.sh" --mode=release) \
    || fail "mac leg failed -- see its log output above"
  MAC_ART="${MAC_ART##*$'\n'}"   # contract: artifact dir = LAST stdout line
  cp "$MAC_ART"/oam-*apple-darwin* "$RELEASE_DIR/"
fi

if [ "$SKIP_LINUX" = "1" ]; then
  warn "OAM_SKIP_LINUX=1 -- linux asset dropped this release"
else
  step "Linux leg (GCP IAP)"
  LINUX_ART=$(bash "$SCRIPT_DIR/build-platforms-gcp-iap.sh" --mode=release) \
    || fail "linux leg failed -- see its log output above"
  LINUX_ART="${LINUX_ART##*$'\n'}"   # contract: artifact dir = LAST stdout line
  cp "$LINUX_ART/oam-x86_64-unknown-linux-gnu" "$RELEASE_DIR/"
fi

# --- assemble + publish ----------------------------------------------------------
step "Assemble release assets + SHA256SUMS"
# Checksums cover the BINARIES only -- the license files are staged after this
# so they do not appear in a manifest install.sh verifies per-asset.
( cd "$RELEASE_DIR" && ls -lh oam-* >&2 && sha256sum oam-* > SHA256SUMS && cat SHA256SUMS >&2 )

# A released binary is a BINARY REDISTRIBUTION of V8 (BSD-3), ICU (Unicode),
# the Node streams port (MIT) and ~380 Rust crates -- every one of which
# requires its notice travel with the distribution. Apache-2.0 section 4(a)
# says the same about oam's own license. Shipping bare binaries met none of
# that, while NOTICE itself asserted the obligation applies to "every released
# oam binary". These three files are small next to a 57MB binary and are the
# difference between the claim and the fact.
step "Stage license + attribution alongside the binaries"
for f in LICENSE NOTICE THIRD_PARTY_LICENSES.md; do
  [ -f "$REPO_DIR/$f" ] || fail "$f missing from the repo -- it must ship with the release"
  cp "$REPO_DIR/$f" "$RELEASE_DIR/$f"
done
ok "LICENSE, NOTICE and THIRD_PARTY_LICENSES.md staged"

if [ "${OAM_DRY_RUN:-0}" = "1" ]; then
  # release.yml's workflow_dispatch dry-run: build + checksum, publish nothing.
  step "DRY RUN -- skipping gh release create"
  ok "assets staged + checksummed at $RELEASE_DIR (nothing published)"
  exit 0
fi

step "Cut GitHub Release $TAG"
# Draft-first publish: assets upload while the release is still a draft, and
# it goes live -- atomically, one API call -- only once every asset is up. A
# mid-upload failure leaves a DRAFT (delete it and re-run), never a live
# half-release that install.sh / self-update could resolve.
gh release create "$TAG" "$RELEASE_DIR"/* \
  --repo "$REPO" \
  --title "$TAG" \
  --generate-notes \
  --verify-tag \
  --draft
gh release edit "$TAG" --repo "$REPO" --draft=false
ok "release $TAG published: https://github.com/$REPO/releases/tag/$TAG"
ok "staged assets kept at $RELEASE_DIR (safe to delete)"

# --- publish the installers to oamjs.org -----------------------------------------
# `oam self-update` fetches https://oamjs.org/install.{sh,ps1} and pipes the
# result into sh / iex. Those files are COPIES of install/ served by a separate
# repo, so without this step the site can silently drift from the release that
# ships with it -- and the failure lands in a user's shell, not in CI.
#
# Skipped rather than fatal when the site checkout is absent: a release is still
# valid without it, and the verification below says loudly if the live site is
# stale.
# --- sidecar regression matrix --------------------------------------------------
# Yaw MCP ships `defaultRuntime: "oam"`, so a release that breaks a sidecar
# breaks the broker for real users. Gating here is the difference between
# catching it and shipping it. Network- and npm-dependent, so a failure to RUN
# the matrix warns; a sidecar that actually fails is fatal.
step "MCP sidecar regression matrix"
if ! command -v node >/dev/null 2>&1; then
  warn "node not on PATH -- sidecar matrix skipped (it hosts the harness, not the test)"
else
  set +e
  # The freshly built NATIVE asset -- the matrix must exercise the binary this
  # release actually ships, not whatever oam happens to be on PATH.
  OAM_BIN="$RELEASE_DIR/oam-aarch64-pc-windows-msvc.exe" node "$REPO_DIR/scripts/mcp-sidecar-matrix.mjs"
  matrix_status=$?
  set -e
  case "$matrix_status" in
    0) ok "every oam-hosted sidecar served its tools" ;;
    1) fail "a sidecar failed on this build -- see above; do NOT ship" ;;
    *) warn "sidecar matrix could not complete (status $matrix_status) -- result is INCOMPLETE, not clean" ;;
  esac
fi

step "Publish installers to oamjs.org"
SITE_DIR="${OAM_SITE_DIR:-$REPO_DIR/../oamjs.org}"
if [ ! -d "$SITE_DIR/public" ]; then
  warn "no site checkout at $SITE_DIR -- installers NOT republished (clone YawLabs/oamjs.org, or set OAM_SITE_DIR)"
else
  cp "$REPO_DIR/install/install.sh" "$SITE_DIR/public/install.sh"
  cp "$REPO_DIR/install/install.ps1" "$SITE_DIR/public/install.ps1"
  if git -C "$SITE_DIR" diff --quiet -- public/install.sh public/install.ps1; then
    ok "oamjs.org installers already match this release"
  else
    git -C "$SITE_DIR" add public/install.sh public/install.ps1
    git -C "$SITE_DIR" commit -q -m "Sync installers from oam $TAG"
    git -C "$SITE_DIR" push -q
    ( cd "$SITE_DIR" && netlify deploy --prod --dir public >/dev/null 2>&1 )       && ok "oamjs.org installers republished"       || warn "netlify deploy failed -- run 'netlify deploy --prod --dir public' in $SITE_DIR"
  fi
fi

# Verify what the SITE actually serves, not what we just uploaded: a stale CDN
# copy is exactly the failure this step exists to prevent, and it is invisible
# from the filesystem.
step "Verify oamjs.org serves this release's installers"
for f in install.sh install.ps1; do
  live="$(curl -fsSL --max-time 30 "https://oamjs.org/$f" 2>/dev/null || true)"
  if [ -z "$live" ]; then
    warn "https://oamjs.org/$f did not fetch -- self-update is BROKEN until it does"
  elif [ "$live" = "$(cat "$REPO_DIR/install/$f")" ]; then
    ok "https://oamjs.org/$f matches install/$f"
  else
    warn "https://oamjs.org/$f DIFFERS from install/$f -- self-update will run the stale copy"
  fi
done
