#!/bin/bash
# =============================================================================
# oam release orchestrator -- replaces .github/workflows/release.yml (removed
# b2f8e24), following the yaw/vew GitHub-Actions-free pattern: local
# orchestrator scripts drive remote build hosts, then `gh release create`
# publishes from this box.
# =============================================================================
# Cuts a GitHub Release for an existing, pushed v* tag with these assets
# (exactly the names install/install.sh, install/install.ps1, and
# `oam self-update` consume):
#
#   oam-aarch64-pc-windows-msvc.exe   local, native (this dev box)
#   oam-x86_64-pc-windows-msvc.exe    local, x64 HOST toolchain under
#                                     Windows-on-ARM emulation (see below)
#   oam-aarch64-apple-darwin          MacBook Air (tailnet), native
#   oam-x86_64-apple-darwin           MacBook Air, x64 HOST toolchain under
#                                     Rosetta 2
#   oam-x86_64-unknown-linux-gnu      GCP Linux VM (IAP), native
#   SHA256SUMS
#
# Why "HOST toolchain under emulation" for the x64 legs: oam cannot
# cross-compile (crates/oam_engine/build.rs -- the V8 startup snapshot must be
# generated by a process of the target architecture). Running the x86_64 HOST
# rustc under the OS's x64 emulation makes host arch == target arch, so the
# snapshot is generated by genuinely-x64 code. Slower than native; correct by
# construction. Each x64 binary is smoke-run under the same emulation before
# it ships.
#
# Compared to the deleted release.yml matrix: the four core targets are all
# still shipped, PLUS aarch64-pc-windows-msvc (which the hosted runners never
# covered on a private repo -- scripts/release-upload-local-arm64.sh used to
# patch it in after the fact; this script makes it a first-class asset).
# aarch64-unknown-linux-gnu remains unshipped (it was public-repo-gated and
# never released; needs an ARM Linux host, e.g. a GCP t2a VM, if wanted).
#
# Gates before anything uploads (ci.yml lived on push; with GHA gone the
# release IS the gate):
#   - scripts/ci-local.sh full (fmt/clippy/build/test/smoke/conformance/
#     node-suite) on this box            [OAM_SKIP_LOCAL_GATE=1 to skip]
#   - gate+test+conformance+node-suite on the Linux VM (inside --mode=release
#     -- the node-suite ratchet was node-compat.yml's ubuntu GATING job)
#   - gate+test on the Mac (inside mac-release)
#
# Usage (tag must exist, be pushed, and HEAD must be on it):
#   git tag v0.7.0 && git push origin v0.7.0
#   ./scripts/release-local.sh v0.7.0
#
# Env knobs:
#   OAM_SKIP_LOCAL_GATE=1   skip the local ci-local.sh run
#   OAM_SKIP_WIN_X64=1      drop the win-x64 asset (emulated build is slow)
#   OAM_SKIP_MAC=1          drop both mac assets (Air unreachable)
#   OAM_SKIP_MAC_X64=1      drop only the mac-x64 asset
#   OAM_SKIP_LINUX=1        drop the linux asset
#   OAM_KEEP_VM=1           leave the GCP VM running after the linux leg
#   OAM_DRY_RUN=1           build + checksum everything, publish nothing
#                           (release.yml's workflow_dispatch dry-run)
#
# The two remote legs run sequentially (simpler failure attribution). If
# release wall-time becomes a problem, they are independent and could run as
# background jobs with per-leg logs -- a future knob, not a v1 need.
#
# Signing seam: binaries ship UNSIGNED + checksummed (the @yawlabs
# distribution model -- scoop/curl/brew fetch bypass Gatekeeper/SmartScreen
# quarantine). To add Apple notarization / Windows Authenticode later, insert
# a signing step where each binary lands in $RELEASE_DIR, before the
# SHA256SUMS step. The rest of the pipeline is unchanged.
# =============================================================================

set -euo pipefail

TAG="${1:?usage: release-local.sh <tag>   (e.g. v0.7.0; tag must exist and be pushed)}"
REPO="YawLabs/oam"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_DIR"

RED='\033[0;31m'; GRN='\033[0;32m'; YEL='\033[1;33m'; CYA='\033[1;36m'; NC='\033[0m'
ok()  { echo -e "${GRN}  [ok]${NC} $*" >&2; }
warn(){ echo -e "${YEL}  [warn]${NC} $*" >&2; }
fail(){ echo -e "${RED}  [fail]${NC} $*" >&2; exit 1; }
step(){ echo -e "\n${CYA}=== $* ===${NC}" >&2; }

SKIP_LOCAL_GATE="${OAM_SKIP_LOCAL_GATE:-0}"
SKIP_WIN_X64="${OAM_SKIP_WIN_X64:-0}"
SKIP_MAC="${OAM_SKIP_MAC:-0}"
SKIP_LINUX="${OAM_SKIP_LINUX:-0}"

RELEASE_DIR="$(mktemp -d -t oam-release-$TAG-XXXXXX)"

# smoke <oam-binary>: ci.yml's smoke assertion, run on every staged binary
# this box can execute (win-arm64 native; win-x64 under the OS emulation).
smoke() {
  local bin="$1" d out
  d="$(mktemp -d)"
  echo "console.log('ci smoke', 6 * 7)" > "$d/smoke.js"
  # Guarded capture: under set -e a crash inside $() would kill the script
  # with no diagnostic and leak $d. 5-min ceiling = ci.yml's
  # timeout-minutes: 5 on the smoke step.
  if ! out="$(timeout 300 "$bin" run "$d/smoke.js")"; then
    rm -rf "$d"
    fail "smoke run failed (crash or 5-min hang) for $bin"
  fi
  rm -rf "$d"
  [ "$out" = "ci smoke 42" ] || fail "smoke output unexpected from $bin: '$out'"
  ok "smoke ok ($bin)"
}

# The gate's conformance + node-suite steps REGENERATE these committed
# artifacts with fresh commit/version stamps -- a prior (or this) run's gate
# self-dirties the tree with them. When they are the ONLY dirty paths,
# restore them to HEAD instead of failing: the content is machine-
# regenerated, reproducible by re-running xtask at this commit, and
# restoring keeps the tree the remote legs tar byte-identical to the tag.
CONFORMANCE_ARTIFACTS=(CONFORMANCE.md CONFORMANCE-NODE.md conformance/scorecard.json conformance/node-suite-scorecard.json)
restore_gate_artifacts() {  # restore_gate_artifacts <context>
  local dirty line path only_artifacts=1
  dirty="$(git status --porcelain)"
  [ -n "$dirty" ] || return 0
  while IFS= read -r line; do
    path="${line:3}"
    case "$path" in
      CONFORMANCE.md | CONFORMANCE-NODE.md | conformance/scorecard.json | conformance/node-suite-scorecard.json) ;;
      *) only_artifacts=0 ;;
    esac
  done <<<"$dirty"
  if [ "$only_artifacts" = "1" ]; then
    warn "$1: discarding gate-regenerated conformance artifacts (reproducible via xtask at this commit)"
    # HEAD explicitly (a bare `checkout --` restores from the INDEX and
    # would leave a staged artifact change dirty behind the warn).
    git checkout HEAD -- "${CONFORMANCE_ARTIFACTS[@]}"
  fi
  return 0
}

# --- preflight ----------------------------------------------------------------
step "Preflight $TAG"
command -v gh >/dev/null 2>&1 || fail "gh CLI not found"
gh auth status >/dev/null 2>&1 || fail "gh not authenticated -- run 'gh auth status' to inspect"

# The release builds from the tag's commit, not whatever HEAD happens to be.
tag_sha="$(git rev-parse "${TAG}^{commit}" 2>/dev/null)" || fail "tag $TAG not found locally -- create and push it first"
head_sha="$(git rev-parse HEAD)"
[ "$tag_sha" = "$head_sha" ] || fail "HEAD ($head_sha) is not the tag commit ($tag_sha) -- checkout the tag first"
# --porcelain, not `git diff --quiet`: untracked files count too -- the
# remote legs tar the WORKING TREE, so an untracked file ships into builds.
# Leftover gate-regenerated conformance stamps (e.g. from a failed prior
# attempt) are auto-restored first; anything else dirty still fails.
restore_gate_artifacts "preflight"
[ -z "$(git status --porcelain)" ] \
  || fail "working tree is dirty (untracked files count -- the remote legs ship the working tree) -- release from a clean tree"

# The binaries report the workspace version -- a v0.7.0 tag over a 0.6.1
# Cargo.toml would ship assets that self-identify wrong.
crate_version="$(awk -F'"' '/^version = /{print $2; exit}' Cargo.toml)"
[ "v$crate_version" = "$TAG" ] \
  || fail "tag $TAG != workspace version $crate_version (Cargo.toml) -- bump the version first"

# Fail on a missing or DIVERGED remote tag NOW, not after an hour of builds
# (gh release create --verify-tag only catches missing, at the very end).
# git rev-parse <tag> and the API's object.sha agree for both lightweight
# (commit SHA) and annotated (tag-object SHA) tags.
remote_tag_obj="$(gh api "repos/$REPO/git/ref/tags/$TAG" --jq .object.sha 2>/dev/null)" \
  || fail "tag $TAG is not on the remote -- push it: git push origin $TAG"
local_tag_obj="$(git rev-parse "$TAG")"
[ "$remote_tag_obj" = "$local_tag_obj" ] \
  || fail "remote tag $TAG ($remote_tag_obj) != local tag ($local_tag_obj) -- local and origin disagree on what $TAG points at"
gh release view "$TAG" --repo "$REPO" >/dev/null 2>&1 \
  && fail "release $TAG already exists on $REPO (possibly a draft left by an interrupted run) -- inspect/delete it: gh release view $TAG --repo $REPO"

[ "$SKIP_MAC" = "1" ]   || [ -n "${OAM_MAC_HOST:-}" ] || fail "OAM_MAC_HOST not set (or set OAM_SKIP_MAC=1 to drop the mac assets)"
[ "$SKIP_LINUX" = "1" ] || command -v gcloud >/dev/null 2>&1 || fail "gcloud CLI not found (or set OAM_SKIP_LINUX=1 to drop the linux asset)"
ok "preflight ok (tag on remote, HEAD == $TAG, tree clean)"

# --- local gate ----------------------------------------------------------------
if [ "$SKIP_LOCAL_GATE" = "1" ]; then
  warn "OAM_SKIP_LOCAL_GATE=1 -- skipping the local CI gate"
else
  step "Local CI gate (scripts/ci-local.sh)"
  bash "$SCRIPT_DIR/ci-local.sh" || fail "local CI gate failed -- fix before releasing"
  # The gate just refreshed the conformance stamps; restore them so the
  # remote legs build from a tree byte-identical to the tag and the release
  # ends with a clean tree (no post-release stamp-refresh commit needed).
  restore_gate_artifacts "post-gate"
fi

# --- local Windows legs ---------------------------------------------------------
step "Build oam-aarch64-pc-windows-msvc.exe (local, native)"
# The resident type-check daemon holds oam.exe open; kill before rebuild.
# (Same precedent as scripts/release-upload-local-arm64.sh.)
taskkill //F //IM oam.exe 2>/dev/null || true
cargo build --release -p oam_cli
cp target/release/oam.exe "$RELEASE_DIR/oam-aarch64-pc-windows-msvc.exe"
smoke "$RELEASE_DIR/oam-aarch64-pc-windows-msvc.exe"

if [ "$SKIP_WIN_X64" = "1" ]; then
  warn "OAM_SKIP_WIN_X64=1 -- win-x64 asset dropped this release"
else
  step "Build oam-x86_64-pc-windows-msvc.exe (local, x64 toolchain under emulation)"
  # --force-non-host: rustup refuses a foreign-host toolchain without it.
  # CARGO_TARGET_DIR isolation keeps the x64 toolchain's host artifacts from
  # churning the native toolchain's fingerprints in target/.
  rustup toolchain install stable-x86_64-pc-windows-msvc --profile minimal --force-non-host
  CARGO_TARGET_DIR=target/x64-host \
    cargo +stable-x86_64-pc-windows-msvc build --release --target x86_64-pc-windows-msvc -p oam_cli
  cp target/x64-host/x86_64-pc-windows-msvc/release/oam.exe "$RELEASE_DIR/oam-x86_64-pc-windows-msvc.exe"
  smoke "$RELEASE_DIR/oam-x86_64-pc-windows-msvc.exe"   # runs under the OS's x64 emulation
fi

# --- remote legs (FAIL-CLOSED: capture, check exit, then consume) ---------------
if [ "$SKIP_MAC" = "1" ]; then
  warn "OAM_SKIP_MAC=1 -- mac assets dropped this release"
else
  step "Mac legs (tailnet: $OAM_MAC_HOST)"
  MAC_ART=$(bash "$SCRIPT_DIR/build-platforms-tailnet.sh" --mode=release) \
    || fail "mac leg failed -- see its log output above"
  MAC_ART="${MAC_ART##*$'\n'}"   # contract: artifact dir = LAST stdout line
  cp "$MAC_ART"/oam-*apple-darwin* "$RELEASE_DIR/"
fi

if [ "$SKIP_LINUX" = "1" ]; then
  warn "OAM_SKIP_LINUX=1 -- linux asset dropped this release"
else
  step "Linux leg (GCP IAP)"
  LINUX_ART=$(bash "$SCRIPT_DIR/build-platforms-gcp-iap.sh" --mode=release) \
    || fail "linux leg failed -- see its log output above"
  LINUX_ART="${LINUX_ART##*$'\n'}"   # contract: artifact dir = LAST stdout line
  cp "$LINUX_ART/oam-x86_64-unknown-linux-gnu" "$RELEASE_DIR/"
fi

# --- assemble + publish ----------------------------------------------------------
step "Assemble release assets + SHA256SUMS"
( cd "$RELEASE_DIR" && ls -lh oam-* >&2 && sha256sum oam-* > SHA256SUMS && cat SHA256SUMS >&2 )

if [ "${OAM_DRY_RUN:-0}" = "1" ]; then
  # release.yml's workflow_dispatch dry-run: build + checksum, publish nothing.
  step "DRY RUN -- skipping gh release create"
  ok "assets staged + checksummed at $RELEASE_DIR (nothing published)"
  exit 0
fi

step "Cut GitHub Release $TAG"
# Draft-first publish: assets upload while the release is still a draft, and
# it goes live -- atomically, one API call -- only once every asset is up. A
# mid-upload failure leaves a DRAFT (delete it and re-run), never a live
# half-release that install.sh / self-update could resolve.
gh release create "$TAG" "$RELEASE_DIR"/* \
  --repo "$REPO" \
  --title "$TAG" \
  --generate-notes \
  --verify-tag \
  --draft
gh release edit "$TAG" --repo "$REPO" --draft=false
ok "release $TAG published: https://github.com/$REPO/releases/tag/$TAG"
ok "staged assets kept at $RELEASE_DIR (safe to delete)"
